-- ============================================================
-- SEED: Base de Conhecimento - Exames Laboratoriais LAMIC
-- PARTE 1 DE 3: Exames 1-70
-- Tenant ID: 004ead16-af22-419c-8e19-28966d4c4d38
-- Neurocore ID: e6c63068-f469-4c49-a3b6-723d07de8303
-- Data: 2026-01-27
-- ============================================================
-- ESTRUTURA: Cada exame será uma base_conhecimento individual
-- ============================================================

DO $$
DECLARE
  v_tenant_id uuid := '004ead16-af22-419c-8e19-28966d4c4d38';
  v_neurocore_id uuid := 'e6c63068-f469-4c49-a3b6-723d07de8303';
  v_domain_id uuid;
  v_base_count integer := 0;
BEGIN
  RAISE NOTICE '============================================================';
  RAISE NOTICE 'Iniciando seed da Base de Conhecimento: Exames';
  RAISE NOTICE '============================================================';

  -- ============================================================
  -- 1. BUSCAR OU CRIAR DOMÍNIO DE CONHECIMENTO
  -- ============================================================
  SELECT id INTO v_domain_id 
  FROM public.knowledge_domains 
  WHERE domain = 'exames' AND neurocore_id = v_neurocore_id;

  -- Se não existe, criar
  IF v_domain_id IS NULL THEN
    INSERT INTO public.knowledge_domains (
      domain,
      neurocore_id,
      active
    ) VALUES (
      'exames',
      v_neurocore_id,
      true
    )
    RETURNING id INTO v_domain_id;
    
    RAISE NOTICE 'Domain criado: %', v_domain_id;
  ELSE
    RAISE NOTICE 'Domain existente: %', v_domain_id;
  END IF;

  -- ============================================================
  -- 2. CRIAR BASES DE CONHECIMENTO (uma para cada exame)
  -- ============================================================

  -- Exame 1: 17 ALFA HIDROXIPROGESTERONA
  INSERT INTO public.base_conhecimentos (
    tenant_id, neurocore_id, name, description, domain, is_active
  ) VALUES (
    v_tenant_id, v_neurocore_id,
    '[17PG] 17 ALFA HIDROXIPROGESTERONA',
    E'[17PG] 17 ALFA HIDROXIPROGESTERONA\nDescrição: Este exame avalia um hormônio ligado às glândulas suprarrenais e exige um jejum mínimo de 8 horas para garantir a precisão dos resultados.\nPerguntas: Precisa de jejum? Sim, no mínimo 8 horas. Informações importantes: Este hormônio avalia as glândulas suprarrenais. Em mulheres, é comum o médico solicitar a coleta em dias específicos do ciclo menstrual.\nPREÇOS: Valor Cheio: R$ 69.00; Cartões de Desconto: R$ 63.00; Planos Funerários: R$ 63.00; Funerária Vida: R$ 59.00; AFAGU: R$ 59.00; LAMIC VIVA+: R$ 54.00; PARTICULAR 02: R$ 39.00',
    v_domain_id, false
  );
  v_base_count := v_base_count + 1;

  -- Exame 2: 25-HIDROXIVITAMINA D
  INSERT INTO public.base_conhecimentos (tenant_id, neurocore_id, name, description, domain, is_active) VALUES (v_tenant_id, v_neurocore_id, '[25-VD3] 25-HIDROXIVITAMINA D', E'[25-VD3] 25-HIDROXIVITAMINA D\nDescrição: Mede as reservas de vitamina D, essencial para ossos e imunidade, sendo importante informar o uso de suplementos, pois certos medicamentos podem interferir no índice medido.\nPerguntas: Precisa de jejum? Geralmente não. Só é necessário jejum de 12h se seus triglicerídeos estiverem muito altos. Quais interferentes? Suplementos de vitamina D e remédios para convulsão ou reumatismo. Orientações: Informe todos os suplementos vitamínicos que você utiliza.\nPREÇOS: Valor Cheio: R$ 110.00; Cartões de Desconto: R$ 87.00; Planos Funerários: R$ 87.00; Funerária Vida: R$ 87.00; AFAGU: R$ 83.00; LAMIC VIVA+: R$ 75.00; PARTICULAR 02: R$ 33.00', v_domain_id, false); v_base_count := v_base_count + 1;

  -- Exame 3: ENDOMISIO IgA
  INSERT INTO public.base_conhecimentos (tenant_id, neurocore_id, name, description, domain, is_active) VALUES (v_tenant_id, v_neurocore_id, '[AAEIGA] ENDOMISIO IgA, ANTICORPOS ANTI', E'[AAEIGA] ENDOMISIO IgA, ANTICORPOS ANTI\nDescrição: É um teste de sangue altamente específico para identificar a sensibilidade ao glúten (doença celíaca), onde resultados positivos geralmente indicam a necessidade de uma dieta restritiva.\nPerguntas: Precisa de jejum? Não. Informações importantes: Usado para investigar a sensibilidade ao glúten. Orientações: Não pare de comer alimentos com glúten (pães, massas) antes do exame, a menos que seu médico mande, para não mascarar o resultado.\nPREÇOS: Valor Cheio: R$ 98.00; Cartões de Desconto: R$ 81.00; Planos Funerários: R$ 81.00; Funerária Vida: R$ 81.00; AFAGU: R$ 81.00; LAMIC VIVA+: R$ 74.00; PARTICULAR 02: R$ 66.00', v_domain_id, false); v_base_count := v_base_count + 1;

  -- Exame 4: VITAMINA C
  INSERT INTO public.base_conhecimentos (tenant_id, neurocore_id, name, description, domain, is_active) VALUES (v_tenant_id, v_neurocore_id, '[AAS] VITAMINA C', E'[AAS] VITAMINA C\nDescrição: Verifica os níveis de vitamina C no organismo para evitar deficiências como o escorbuto, exigindo jejum de 8 horas e cuidados especiais de proteção da amostra contra a luz.\nPerguntas: Precisa de jejum? Sim, no mínimo 8 horas. Qual preparo? Evite tomar suplementos de vitamina C ou sucos cítricos em excesso no dia anterior. Informações importantes: Esta vitamina é sensível à luz, exigindo cuidado rápido na coleta.\nPREÇOS: Valor Cheio: R$ 110.00; Funerária Vida: R$ 85.00; AFAGU: R$ 85.00; LAMIC VIVA+: R$ 85.00; PARTICULAR 02: R$ 55.00', v_domain_id, false); v_base_count := v_base_count + 1;

  -- Exame 5: ÁCIDO FÓLICO
  INSERT INTO public.base_conhecimentos (tenant_id, neurocore_id, name, description, domain, is_active) VALUES (v_tenant_id, v_neurocore_id, '[AFOL] ÁCIDO FÓLICO', E'[AFOL] ÁCIDO FÓLICO\nDescrição: Avalia a vitamina B9, fundamental para a formação do sangue e saúde na gravidez, sendo uma análise sensível que requer que o sangue seja protegido da luz desde a coleta.\nPerguntas: Precisa de jejum? Não. Quais interferentes? Bebidas alcoólicas e alguns medicamentos. Informações importantes: Essencial para a saúde das células do sangue e desenvolvimento do bebê na gravidez. A amostra não pode pegar luz.\nPREÇOS: Valor Cheio: R$ 56.00; Cartões de Desconto: R$ 44.00; Planos Funerários: R$ 44.00; Funerária Vida: R$ 35.00; AFAGU: R$ 43.00; LAMIC VIVA+: R$ 43.00', v_domain_id, false); v_base_count := v_base_count + 1;

  -- Exame 6: HBS, ANTI - HEPATITE B
  INSERT INTO public.base_conhecimentos (tenant_id, neurocore_id, name, description, domain, is_active) VALUES (v_tenant_id, v_neurocore_id, '[AHBS] HBS, ANTI - HEPATITE B', E'[AHBS] HBS, ANTI - HEPATITE B\nDescrição: Este teste verifica se o paciente possui imunidade contra a Hepatite B, seja por ter tomado a vacina ou por já ter superado a infecção no passado.\nPerguntas: Precisa de jejum? Não. Qual preparo? Se usar o remédio Heparina, colha o sangue antes da próxima dose. Informações importantes: Serve para saber se você está vacinado ou se já se curou de uma infecção passada.\nPREÇOS: Valor Cheio: R$ 68.00; Cartões de Desconto: R$ 61.00; Planos Funerários: R$ 61.00; Funerária Vida: R$ 60.00; AFAGU: R$ 59.00; LAMIC VIVA+: R$ 56.00; PARTICULAR 02: R$ 46.00', v_domain_id, false); v_base_count := v_base_count + 1;

  -- Exame 7: TRAB
  INSERT INTO public.base_conhecimentos (tenant_id, neurocore_id, name, description, domain, is_active) VALUES (v_tenant_id, v_neurocore_id, '[AIT] TRAB- ANTICORPO ANTI- RECEPTOR TSH', E'[AIT] TRAB- ANTICORPO ANTI- RECEPTOR TSH\nDescrição: Utilizado para diagnosticar doenças autoimunes da tireoide, como a Doença de Graves, sendo fundamental informar o uso de fórmulas para emagrecer que podem alterar o resultado.\nPerguntas: Precisa de jejum? Não. Qual preparo? Informe se usa fórmulas para emagrecer ou biotina. Informações importantes: Ajuda a diagnosticar se a tireoide está acelerada por uma causa autoimune (Doença de Graves).\nPREÇOS: Valor Cheio: R$ 96.00; Cartões de Desconto: R$ 70.00; Planos Funerários: R$ 70.00; Funerária Vida: R$ 66.00; AFAGU: R$ 66.00; LAMIC VIVA+: R$ 64.00; PARTICULAR 02: R$ 66.00', v_domain_id, false); v_base_count := v_base_count + 1;

  -- Exame 8: ALBUMINA
  INSERT INTO public.base_conhecimentos (tenant_id, neurocore_id, name, description, domain, is_active) VALUES (v_tenant_id, v_neurocore_id, '[ALB] ALBUMINA', E'[ALB] ALBUMINA\nDescrição: Mede a principal proteína fabricada pelo fígado para avaliar o estado nutricional e a saúde dos órgãos vitais, não necessitando de preparo ou jejum específico.\nPerguntas: Precisa de jejum? Não. Informações importantes: Avalia seu estado de nutrição e a saúde do fígado. Orientações: Não exige preparo especial, mas procure estar bem hidratado.\nPREÇOS: Valor Cheio: R$ 27.00; Cartões de Desconto: R$ 22.00; Planos Funerários: R$ 22.00; Funerária Vida: R$ 22.00; AFAGU: R$ 21.00; LAMIC VIVA+: R$ 19.00; PARTICULAR 02: R$ 18.00', v_domain_id, false); v_base_count := v_base_count + 1;

  -- Exame 9: AMILASE
  INSERT INTO public.base_conhecimentos (tenant_id, neurocore_id, name, description, domain, is_active) VALUES (v_tenant_id, v_neurocore_id, '[AMI] AMILASE', E'[AMI] AMILASE\nDescrição: Analisa uma enzima do pâncreas e das glândulas salivares para investigar inflamações nessas regiões, sendo um indicador rápido para casos de dores abdominais suspeitas.\nPerguntas: Precisa de jejum? Não. Informações importantes: Avalia inflamações no pâncreas ou nas glândulas salivares. Quais interferentes? Informe se usa o medicamento Icodextrina.\nPREÇOS: Valor Cheio: R$ 27.00; Cartões de Desconto: R$ 24.00; Planos Funerários: R$ 24.00; Funerária Vida: R$ 27.00; AFAGU: R$ 21.00; LAMIC VIVA+: R$ 19.00; PARTICULAR 02: R$ 19.00', v_domain_id, false); v_base_count := v_base_count + 1;

  -- Exame 10: HBsAg
  INSERT INTO public.base_conhecimentos (tenant_id, neurocore_id, name, description, domain, is_active) VALUES (v_tenant_id, v_neurocore_id, '[AU-P2] HBsAg', E'[AU-P2] HBsAg\nDescrição: É o exame que detecta a presença atual do vírus da Hepatite B no corpo, sendo o primeiro sinal a aparecer no sangue após o contágio.\nPerguntas: Precisa de jejum? Não. Informações importantes: É o teste para saber se o vírus da Hepatite B está presente no seu corpo agora. Atenção: Vacinação recente pode alterar o resultado temporariamente.\nPREÇOS: Valor Cheio: R$ 71.00; Cartões de Desconto: R$ 48.00; Planos Funerários: R$ 48.00; Funerária Vida: R$ 47.00; AFAGU: R$ 45.00; LAMIC VIVA+: R$ 42.00; PARTICULAR 02: R$ 38.00', v_domain_id, false); v_base_count := v_base_count + 1;

  -- Continuando com TODOS os exames em formato compacto...
  INSERT INTO public.base_conhecimentos (tenant_id, neurocore_id, name, description, domain, is_active) VALUES 
  (v_tenant_id, v_neurocore_id, '[AUR] ÁCIDO ÚRICO', E'[AUR] ÁCIDO ÚRICO\nDescrição: Mede o resíduo da digestão de certas proteínas e ajuda a investigar casos de gota ou pedras nos rins, podendo sofrer influência do uso de dipirona ou diuréticos.\nPerguntas: Precisa de jejum? Não. Quais interferentes? Dipirona (Metamizol) e Aspirina podem dar resultados falsamente baixos. Orientações: Evite bebidas alcoólicas e carnes vermelhas em excesso no dia anterior.\nPREÇOS: Valor Cheio: R$ 27.00; Cartões de Desconto: R$ 22.00; Planos Funerários: R$ 22.00; Funerária Vida: R$ 22.00; AFAGU: R$ 21.00; LAMIC VIVA+: R$ 19.00; PARTICULAR 02: R$ 18.00', v_domain_id, false),
  (v_tenant_id, v_neurocore_id, '[B-HCGLP2] BETA GONADOTROFINA CORIÔNICA - BHCG QUALITATIVO', E'[B-HCGLP2] BETA GONADOTROFINA CORIÔNICA - BHCG QUALITATIVO\nDescrição: É o teste padrão para confirmar a gravidez através da detecção do hormônio específico no sangue, recomendado preferencialmente após dois dias de atraso menstrual.\nPerguntas: Precisa de jejum? Não. Orientações: Recomendado após 2 dias de atraso menstrual. Informações importantes: É necessário apresentar documento original com foto. Menores de 18 anos precisam de acompanhante ou pedido médico.\nPREÇOS: Valor Cheio: R$ 29.00; Cartões de Desconto: R$ 28.00; Planos Funerários: R$ 28.00; Funerária Vida: R$ 30.00; AFAGU: R$ 27.00; LAMIC VIVA+: R$ 27.00; PARTICULAR 02: R$ 27.00', v_domain_id, false),
  (v_tenant_id, v_neurocore_id, '[B12] VITAMINA B12', E'[B12] VITAMINA B12\nDescrição: Essencial para o sistema nervoso e a formação do sangue, este exame avalia se os níveis de vitamina B12 estão adequados, sendo especialmente importante para vegetarianos estritos e pacientes que usam metformina ou fizeram cirurgia bariátrica.\nPerguntas: Precisa de jejum? Não. Quais interferentes? Metformina (para diabetes) e anticoncepcionais. Informações importantes: Vital para os nervos e memória. Comum baixar em vegetarianos ou após cirurgia bariátrica.\nPREÇOS: Valor Cheio: R$ 65.00; Cartões de Desconto: R$ 53.00; Planos Funerários: R$ 53.00; Funerária Vida: R$ 52.00; AFAGU: R$ 50.00; LAMIC VIVA+: R$ 47.00; PARTICULAR 02: R$ 44.00', v_domain_id, false),
  (v_tenant_id, v_neurocore_id, '[B12-P2] VITAMINA B12', E'[B12-P2] VITAMINA B12\nDescrição: Este teste mede a vitamina B12 no organismo para prevenir anemias e problemas neurológicos; é recomendável informar o uso de vitaminas ou medicamentos, pois anticoncepcionais e outros remédios podem reduzir o resultado.\nPerguntas: Precisa de jejum? Não. Informações importantes: Mesmo exame que o anterior. Orientações: Informe se você toma injeções ou comprimidos de vitaminas, pois isso altera o valor esperado.\nPREÇOS: Valor Cheio: R$ 62.00; Cartões de Desconto: R$ 53.00; Planos Funerários: R$ 53.00; Funerária Vida: R$ 52.00; AFAGU: R$ 50.00; LAMIC VIVA+: R$ 47.00; PARTICULAR 02: R$ 29.00', v_domain_id, false),
  (v_tenant_id, v_neurocore_id, '[BHCG] BETA GONADOTROFINA CORIÔNICA - BHCG', E'[BHCG] BETA GONADOTROFINA CORIÔNICA - BHCG\nDescrição: Versão detalhada do teste de gravidez que mede a quantidade exata do hormônio no sangue, sendo ideal para acompanhar o início da gestação ou tratamentos de fertilidade; deve ser feito preferencialmente após atraso menstrual.\nPerguntas: Precisa de jejum? Não. Qual preparo? É obrigatório apresentar documento original com foto. Se for menor de 18 anos, deve estar acompanhada pelos pais ou ter pedido médico. Orientações: O ideal é realizar o exame após 2 dias de atraso menstrual. Informe a data da sua última menstruação.\nPREÇOS: Valor Cheio: R$ 65.00; Cartões de Desconto: R$ 40.00; Planos Funerários: R$ 40.00; Funerária Vida: R$ 35.00; AFAGU: R$ 35.00; LAMIC VIVA+: R$ 33.00; PARTICULAR 02: R$ 33.00', v_domain_id, false),
  (v_tenant_id, v_neurocore_id, '[BIL] BILIRRUBINA', E'[BIL] BILIRRUBINA\nDescrição: Este exame avalia o funcionamento do fígado e a saúde dos glóbulos vermelhos, ajudando a identificar causas de pele e olhos amarelados; a amostra de sangue precisa ser protegida da luz para não alterar o resultado.\nPerguntas: Precisa de jejum? Não. Informações importantes: Este exame avalia a saúde do fígado e se há destruição excessiva de glóbulos vermelhos (anemia). Qual preparo? A amostra de sangue não pode pegar luz; o laboratório usará um frasco especial ou papel alumínio para protegê-la.\nPREÇOS: Valor Cheio: R$ 67.00; Cartões de Desconto: R$ 31.00; Planos Funerários: R$ 31.00; Funerária Vida: R$ 30.00; AFAGU: R$ 29.00; LAMIC VIVA+: R$ 27.00; PARTICULAR 02: R$ 22.00', v_domain_id, false),
  (v_tenant_id, v_neurocore_id, '[BIOPS] BIOPSIA SIMPLES', E'[BIOPS] BIOPSIA SIMPLES\nDescrição: Consiste na análise de um pequeno pedaço de tecido retirado pelo médico para identificar a natureza de lesões ou tumores; o material deve ser enviado ao laboratório conservado em formol para garantir uma análise precisa.\nPerguntas: Precisa de jejum? O jejum depende do tipo de pequena cirurgia para retirar o material; confirme com seu médico. Orientações: É obrigatório entregar o pedido médico especificando o local exato da coleta. Informações importantes: O material deve ser colocado imediatamente em um frasco com formol para não estragar.\nPREÇOS: Valor Cheio: R$ 193.00; Cartões de Desconto: R$ 172.00; Planos Funerários: R$ 172.00; Funerária Vida: R$ 171.00; AFAGU: R$ 164.00; LAMIC VIVA+: R$ 156.00; PARTICULAR 02: R$ 116.00', v_domain_id, false),
  (v_tenant_id, v_neurocore_id, '[C125] CA 125', E'[C125] CA 125\nDescrição: Um marcador utilizado para acompanhar a saúde dos ovários e monitorar tratamentos, embora possa aumentar também em situações simples como menstruação, cistos ou endometriose.\nPerguntas: Precisa de jejum? Não. Informações importantes: É um marcador usado principalmente para acompanhar o tratamento de câncer de ovário. Atenção: Os níveis podem subir naturalmente durante a menstruação, gravidez ou em casos de endometriose, por isso o médico deve interpretar o resultado com cautela.\nPREÇOS: Valor Cheio: R$ 89.00; Cartões de Desconto: R$ 46.00; Planos Funerários: R$ 46.00; Funerária Vida: R$ 45.00; AFAGU: R$ 43.00; LAMIC VIVA+: R$ 40.00; PARTICULAR 02: R$ 40.00', v_domain_id, false),
  (v_tenant_id, v_neurocore_id, '[C199] CA 19-9', E'[C199] CA 19-9\nDescrição: Utilizado principalmente para monitorar o tratamento de problemas no pâncreas e nas vias biliares, servindo como uma ferramenta de acompanhamento para o médico avaliar a evolução de inflamações ou tumores.\nPerguntas: Precisa de jejum? Não. Informações importantes: Usado para monitorar tumores no pâncreas ou nas vias biliares. Atenção: Inflamações no fígado ou pancreatite também podem elevar esse marcador, mesmo sem a presença de tumores.\nPREÇOS: Funerária Vida: R$ 60.00; AFAGU: R$ 60.00; LAMIC VIVA+: R$ 56.00; PARTICULAR 02: R$ 49.00', v_domain_id, false),
  (v_tenant_id, v_neurocore_id, '[CA] CÁLCIO', E'[CA] CÁLCIO\nDescrição: Mede a quantidade total de cálcio no sangue para checar a saúde dos ossos, dentes e o funcionamento dos músculos e rins, ajudando a identificar se as glândulas paratireoides estão trabalhando bem.\nPerguntas: Precisa de jejum? Não. Informações importantes: Mede o cálcio total para avaliar a saúde dos ossos, dentes, músculos e coração. Orientações: Ajuda o médico a investigar problemas nos rins ou falta de vitamina D.\nPREÇOS: Valor Cheio: R$ 27.00; Cartões de Desconto: R$ 22.00; Planos Funerários: R$ 22.00; Funerária Vida: R$ 22.00; AFAGU: R$ 21.00; LAMIC VIVA+: R$ 19.00; PARTICULAR 02: R$ 18.00', v_domain_id, false);
  
  v_base_count := v_base_count + 7;

  -- Exames 18-60: Bloco 1
  INSERT INTO public.base_conhecimentos (tenant_id, neurocore_id, name, description, domain, is_active) VALUES 
  (v_tenant_id, v_neurocore_id, '[CAI] CÁLCIO IÔNICO', E'[CAI] CÁLCIO IÔNICO\nDescrição: Mede a parte ativa do cálcio no sangue que está pronta para ser usada pelo corpo, sendo um teste muito sensível para avaliar nervos e músculos, exigindo uma coleta cuidadosa e rápida.\nPerguntas: Precisa de jejum? Não. Qual preparo? A coleta deve ser feita com o mínimo de tempo de "garrote" (o elástico no braço) para não alterar o resultado. Informações importantes: Mede a parte do cálcio que está realmente "trabalhando" no corpo no momento.\nPREÇOS: Valor Cheio: R$ 73.00; Cartões de Desconto: R$ 56.00; Planos Funerários: R$ 56.00; Funerária Vida: R$ 55.00; AFAGU: R$ 52.00; LAMIC VIVA+: R$ 51.00; PARTICULAR 02: R$ 19.00', v_domain_id, false),
  (v_tenant_id, v_neurocore_id, '[CAL-F2] CALPROTECTINA FECAL', E'[CAL-F2] CALPROTECTINA FECAL\nDescrição: Exame de fezes que identifica se há inflamação ativa no intestino, ajudando o médico a diferenciar doenças mais sérias, como a Doença de Crohn, de problemas intestinais funcionais mais leves.\nPerguntas: Precisa de jejum? Não. Qual preparo? Evite o uso de laxantes, antiácidos ou supositórios antes da coleta. Orientações: Colete frações de diferentes partes das fezes. O material deve ser mantido na geladeira e entregue em até 24 horas. Ajuda a diferenciar inflamação intestinal de "intestino irritável".\nPREÇOS: Valor Cheio: R$ 208.00; Cartões de Desconto: R$ 170.00; Planos Funerários: R$ 170.00; Funerária Vida: R$ 170.00; AFAGU: R$ 166.00; LAMIC VIVA+: R$ 151.00; PARTICULAR 02: R$ 165.00', v_domain_id, false),
  (v_tenant_id, v_neurocore_id, '[CEA] CEA - ANTÍGENO CARCINOEMBRIONÁRIO', E'[CEA] CEA - ANTÍGENO CARCINOEMBRIONÁRIO\nDescrição: Funciona como um sinalizador para acompanhar o tratamento de doenças no intestino; como o fumo e inflamações podem elevar seus níveis, ele é usado principalmente para monitorar quem já está em tratamento.\nPerguntas: Precisa de jejum? Não. Informações importantes: Marcador usado para monitorar tratamentos de câncer, especialmente o de intestino. Atenção: Pessoas que fumam costumam ter níveis naturalmente mais altos deste marcador.\nPREÇOS: Valor Cheio: R$ 89.00; Cartões de Desconto: R$ 66.00; Planos Funerários: R$ 66.00; Funerária Vida: R$ 66.00; AFAGU: R$ 63.00; LAMIC VIVA+: R$ 60.00; PARTICULAR 02: R$ 55.00', v_domain_id, false),
  (v_tenant_id, v_neurocore_id, '[CITO] CITOPATOLÓGICO - COLO DO ÚTERO', E'[CITO] CITOPATOLÓGICO - COLO DO ÚTERO\nDescrição: Conhecido como Papanicolau, é essencial para prevenir o câncer do colo do útero ao detectar alterações nas células antes que virem doenças graves; requer que a paciente evite relações sexuais e cremes vaginais nos dias anteriores.\nPerguntas: Precisa de jejum? Não. Qual preparo? Não use duchas, cremes ou pomadas vaginais por 48h antes. Não tenha relações sexuais por 3 dias antes. Orientações: Aguarde 48h após o fim da menstruação. Este exame (Papanicolau) é vital para prevenir o câncer de colo de útero.\nPREÇOS: Valor Cheio: R$ 128.00; Cartões de Desconto: R$ 75.00; Planos Funerários: R$ 75.00; Funerária Vida: R$ 75.00; AFAGU: R$ 75.00; LAMIC VIVA+: R$ 75.00; PARTICULAR 02: R$ 77.00', v_domain_id, false),
  (v_tenant_id, v_neurocore_id, '[CITRA-A] CITRATO - URINA 24H', E'[CITRA-A] CITRATO - URINA 24H\nDescrição: Utilizado para investigar a causa de pedras nos rins, este exame exige que o paciente colete toda a urina de um dia inteiro em um frasco especial, mantendo-a refrigerada, para medir a quantidade de ácido cítrico que ajuda a prevenir os cálculos.\nPerguntas: Precisa de jejum? Não. Qual preparo? Você deve retirar o frasco especial no laboratório antes de começar. Despreze a primeira urina do dia e, a partir daí, guarde todas as outras por 24 horas. Informações importantes: Mantenha o frasco na geladeira durante todo o processo. Contraindicações: Evite colher durante o período menstrual para não contaminar a amostra com sangue.\nPREÇOS: Valor Cheio: R$ 59.00; Cartões de Desconto: R$ 43.00; Planos Funerários: R$ 43.00; Funerária Vida: R$ 43.00; AFAGU: R$ 43.00; LAMIC VIVA+: R$ 37.00; PARTICULAR 02: R$ 35.00', v_domain_id, false),
  (v_tenant_id, v_neurocore_id, '[CLO] CLORO', E'[CLO] CLORO\nDescrição: Mede o nível de um sal mineral importante para o equilíbrio de líquidos e a acidez do corpo, sendo que seus valores costumam acompanhar os do sódio e podem sofrer pequenas variações naturais logo após as refeições.\nPerguntas: Precisa de jejum? Não é necessário. Quais interferentes? Medicamentos como Salicilato, Brometo e Iodo podem afetar o resultado; informe o que está usando. Informações importantes: O cloro ajuda a manter o equilíbrio de líquidos e a acidez do corpo. Os níveis podem sofrer leves variações logo após as refeições.\nPREÇOS: Valor Cheio: R$ 27.00; Cartões de Desconto: R$ 22.00; Planos Funerários: R$ 22.00; Funerária Vida: R$ 22.00; AFAGU: R$ 21.00; LAMIC VIVA+: R$ 19.00; PARTICULAR 02: R$ 18.00', v_domain_id, false),
  (v_tenant_id, v_neurocore_id, '[CML] CITOPATOLÓGICO EM MEIO LÍQUIDO', E'[CML] CITOPATOLÓGICO EM MEIO LÍQUIDO\nDescrição: Uma versão mais moderna do Papanicolau que utiliza um líquido conservante para limpar impurezas da amostra, permitindo que o médico visualize melhor as células do colo do útero e identifique lesões de forma mais precisa.\nPerguntas: Precisa de jejum? Não. Qual preparo? Não use cremes vaginais nem tenha relações sexuais nas 48h-72h antes. Informações importantes: É uma versão moderna do Papanicolau que permite detectar sinais de câncer de colo de útero com maior clareza. Orientações: É obrigatório levar o pedido médico e não estar no período menstrual.\nPREÇOS: Valor Cheio: R$ 192.00; Cartões de Desconto: R$ 172.00; Planos Funerários: R$ 172.00; Funerária Vida: R$ 170.00; AFAGU: R$ 155.00; LAMIC VIVA+: R$ 140.00', v_domain_id, false),
  (v_tenant_id, v_neurocore_id, '[CMVG] CITOMEGALOVÍRUS IGG, ANTICORPOS', E'[CMVG] CITOMEGALOVÍRUS IGG, ANTICORPOS\nDescrição: Este teste verifica se a pessoa já entrou em contato com o Citomegalovírus em algum momento da vida, identificando se o corpo já possui uma "memória" de defesa contra esse vírus comum.\nPerguntas: Precisa de jejum? Não (para bebês, colher entre as mamadas). Informações importantes: Indica se você já teve contato com o Citomegalovírus em algum momento da vida. Orientações: Se o resultado for "reagente", significa que você tem imunidade ou uma infecção antiga que o corpo já combateu.\nPREÇOS: Valor Cheio: R$ 59.00; Cartões de Desconto: R$ 48.00; Planos Funerários: R$ 48.00; Funerária Vida: R$ 48.00; AFAGU: R$ 48.00; LAMIC VIVA+: R$ 43.00; PARTICULAR 02: R$ 49.00', v_domain_id, false),
  (v_tenant_id, v_neurocore_id, '[CMVM] CITOMEGALOVÍRUS IGM, ANTICORPOS', E'[CMVM] CITOMEGALOVÍRUS IGM, ANTICORPOS\nDescrição: Exame importante para identificar se há uma infecção ativa ou muito recente pelo Citomegalovírus, sendo especialmente monitorado em gestantes e pessoas com o sistema de defesa enfraquecido.\nPerguntas: Precisa de jejum? Não. Informações importantes: Identifica se há uma infecção ativa ou muito recente. Orientações: Informe se está grávida ou se já fez este exame antes, pois o IgM pode permanecer positivo por meses após a infecção ter passado.\nPREÇOS: Valor Cheio: R$ 59.00; Cartões de Desconto: R$ 48.00; Planos Funerários: R$ 48.00; Funerária Vida: R$ 48.00; AFAGU: R$ 48.00; LAMIC VIVA+: R$ 43.00; PARTICULAR 02: R$ 49.00', v_domain_id, false),
  (v_tenant_id, v_neurocore_id, '[COAG] COAGULOGRAMA COMPLETO', E'[COAG] COAGULOGRAMA COMPLETO\nDescrição: Conjunto de testes que avalia a rapidez com que o sangue estanca, sendo essencial antes de cirurgias ou para quem usa remédios para "afinar" o sangue; é obrigatório informar todos os medicamentos em uso antes da coleta.\nPerguntas: Precisa de jejum? Não. Qual preparo? Informe todos os remédios, especialmente anticoagulantes (como varfarina), aspirina e antibióticos. Informações importantes: Avalia se sua coagulação está normal, sendo essencial antes de cirurgias. Orientações: O tubo de coleta deve ser preenchido totalmente para o teste ser confiável.\nPREÇOS: Valor Cheio: R$ 74.00; Cartões de Desconto: R$ 37.00; Planos Funerários: R$ 37.00; Funerária Vida: R$ 37.00; AFAGU: R$ 36.00; LAMIC VIVA+: R$ 34.00; PARTICULAR 02: R$ 27.00', v_domain_id, false);
  
  v_base_count := v_base_count + 10;

  -- Continuando com todos os exames restantes em blocos...
  INSERT INTO public.base_conhecimentos (tenant_id, neurocore_id, name, description, domain, is_active) VALUES 
  (v_tenant_id, v_neurocore_id, '[COBRE-S] COBRE', E'[COBRE-S] COBRE\nDescrição: Mede a quantidade deste mineral no sangue, que é vital para a saúde dos tecidos e do sangue, ajudando a identificar tanto a falta quanto o excesso tóxico de cobre no organismo.\nPerguntas: Precisa de jejum? Não. Informações importantes: Mede o cobre, mineral vital para o sangue e tecidos. Orientações: Se for colher outros exames, o de cobre deve ser o primeiro. Informe se usa anticoncepcionais ou suplementos de zinco e ferro, pois eles interferem na absorção do cobre.\nPREÇOS: Valor Cheio: R$ 59.00; Cartões de Desconto: R$ 41.00; Planos Funerários: R$ 41.00; Funerária Vida: R$ 38.00; AFAGU: R$ 38.00; LAMIC VIVA+: R$ 34.00; PARTICULAR 02: R$ 33.00', v_domain_id, false),
  (v_tenant_id, v_neurocore_id, '[COPR] COPROLOGIA FUNCIONAL', E'[COPR] COPROLOGIA FUNCIONAL\nDescrição: Análise completa das fezes que avalia como o corpo está digerindo os alimentos e absorvendo nutrientes, ajudando a descobrir a causa de dores abdominais, inflamações ou a presença de parasitas.\nPerguntas: Precisa de jejum? Não. Qual preparo? Evite laxantes, supositórios e bebidas alcoólicas ou gasosas nos 3 dias anteriores. Informações importantes: Analisa como seu sistema digestivo absorve nutrientes. Orientações: Colha a amostra em um recipiente limpo e entregue em até 2 horas ou mantenha refrigerado.\nPREÇOS: Valor Cheio: R$ 59.00; Cartões de Desconto: R$ 33.00; Planos Funerários: R$ 33.00; Funerária Vida: R$ 32.00; AFAGU: R$ 31.00; LAMIC VIVA+: R$ 29.00; PARTICULAR 02: R$ 22.00', v_domain_id, false),
  (v_tenant_id, v_neurocore_id, '[CORTIB] CORTISOL', E'[CORTIB] CORTISOL\nDescrição: Mede o chamado "hormônio do estresse", que regula o metabolismo; como seus níveis variam muito durante o dia, a coleta deve ser feita rigorosamente entre 7h e 9h da manhã para garantir um resultado confiável.\nPerguntas: Precisa de jejum? Não. Qual preparo? A coleta deve ser feita preferencialmente às 8h da manhã. Informe o uso de pomadas, cremes ou anticoncepcionais. Informações importantes: Conhecido como "hormônio do estresse", ele varia muito durante o dia, por isso o horário da coleta é rígido.\nPREÇOS: Valor Cheio: R$ 59.00; Cartões de Desconto: R$ 46.00; Planos Funerários: R$ 46.00; Funerária Vida: R$ 45.00; AFAGU: R$ 45.00; LAMIC VIVA+: R$ 43.00', v_domain_id, false),
  (v_tenant_id, v_neurocore_id, '[CPK] CREATINOFOSFOQUINASE - CPK', E'[CPK] CREATINOFOSFOQUINASE - CPK\nDescrição: Esta enzima indica como está a saúde dos músculos e do coração; como ela aumenta após pancadas ou esforços físicos pesados, recomenda-se não fazer exercícios intensos nos 7 dias antes do exame.\nPerguntas: Precisa de jejum? Não. Qual preparo? Não pratique exercícios físicos intensos nos 7 dias anteriores à coleta. Informações importantes: Essa enzima indica desgaste ou lesão muscular. Orientações: Injeções musculares recentes ou pancadas podem elevar o resultado.\nPREÇOS: Valor Cheio: R$ 61.00; Cartões de Desconto: R$ 48.00; Planos Funerários: R$ 48.00; Funerária Vida: R$ 47.00; AFAGU: R$ 45.00; LAMIC VIVA+: R$ 43.00; PARTICULAR 02: R$ 19.00', v_domain_id, false),
  (v_tenant_id, v_neurocore_id, '[CRE] CREATININA', E'[CRE] CREATININA\nDescrição: O principal exame para checar a saúde dos rins, pois mede uma substância produzida pelos músculos que os rins devem filtrar; o resultado permite calcular com precisão a capacidade de filtragem do corpo.\nPerguntas: Precisa de jejum? Não. Qual preparo? Se possível, colha antes de tomar remédios para dor (como Dipirona). Informações importantes: É o melhor indicador de como seus rins estão filtrando o sangue. Orientações: Informe se usa suplementos de creatina para academia, pois eles elevam o nível no exame.\nPREÇOS: Valor Cheio: R$ 27.00; Cartões de Desconto: R$ 22.00; Planos Funerários: R$ 22.00; Funerária Vida: R$ 22.00; AFAGU: R$ 21.00; LAMIC VIVA+: R$ 19.00; PARTICULAR 02: R$ 16.00', v_domain_id, false),
  (v_tenant_id, v_neurocore_id, '[CTOT] COLESTEROL TOTAL', E'[CTOT] COLESTEROL TOTAL\nDescrição: Avalia a quantidade de gordura no sangue para medir o risco de entupimento das artérias e problemas cardíacos, sendo recomendável não ingerir bebidas alcoólicas nos três dias anteriores à coleta.\nPerguntas: Precisa de jejum? Geralmente não. Quais interferentes? Bebidas alcoólicas alteram o resultado; recomenda-se ficar 72h sem beber antes da coleta. Informações importantes: Avalia o risco de gordura acumulada nas artérias. Orientações: Informe se usa Vitamina C ou remédios para pressão (Metildopa).\nPREÇOS: Valor Cheio: R$ 27.00; Cartões de Desconto: R$ 22.00; Planos Funerários: R$ 22.00; Funerária Vida: R$ 21.00; AFAGU: R$ 18.00; LAMIC VIVA+: R$ 18.00; PARTICULAR 02: R$ 16.00', v_domain_id, false),
  (v_tenant_id, v_neurocore_id, '[CULT] CULTURA COM ANTIBIOGRAMA', E'[CULT] CULTURA COM ANTIBIOGRAMA\nDescrição: Procedimento que identifica qual bactéria está causando uma infecção e testa quais antibióticos são capazes de matá-la, garantindo que o tratamento escolhido pelo médico seja o mais certeiro possível.\nPerguntas: Precisa de jejum? Não. Qual preparo? O ideal é colher ANTES de começar a tomar antibióticos. Se já estiver tomando, avise o nome do remédio. Informações importantes: Descobre qual bactéria causa a infecção e qual remédio a mata. Orientações: Para urina, faça uma higiene rigorosa da região genital antes de colher.\nPREÇOS: Valor Cheio: R$ 78.00; Cartões de Desconto: R$ 50.00; Planos Funerários: R$ 50.00; Funerária Vida: R$ 49.00; AFAGU: R$ 47.00; LAMIC VIVA+: R$ 42.00; PARTICULAR 02: R$ 34.00', v_domain_id, false),
  (v_tenant_id, v_neurocore_id, '[D1] IGE ESPECIFICO DERMATOPHAGOIDES PTERONYSSINUS (D1)', E'[D1] IGE ESPECIFICO DERMATOPHAGOIDES PTERONYSSINUS (D1)\nDescrição: Um teste de alergia que identifica se o paciente tem sensibilidade ao ácaro mais comum da poeira doméstica, ajudando a descobrir a causa de crises de rinite e asma.\nPerguntas: Precisa de jejum? Não. Informações importantes: Identifica alergia específica ao ácaro da poeira doméstica. Orientações: Ajuda a descobrir a causa de crises de asma, rinite ou coceiras constantes em ambientes fechados.\nPREÇOS: Valor Cheio: R$ 53.00; AFAGU: R$ 43.00; LAMIC VIVA+: R$ 37.00; PARTICULAR 02: R$ 44.00', v_domain_id, false),
  (v_tenant_id, v_neurocore_id, '[DHES] SULFATO DE DEHIDROEPIANDROSTERONA', E'[DHES] SULFATO DE DEHIDROEPIANDROSTERONA\nDescrição: Este exame mede um hormônio produzido pelas glândulas suprarrenais que serve como base para a produção de outros hormônios masculinos e femininos, auxiliando na investigação de alterações hormonais.\nPerguntas: Para que serve? Avalia a produção de hormônios masculinos pelas glândulas suprarrenais. Informações importantes: Muito utilizado para investigar causas de excesso de pelos, acne ou irregularidade menstrual em mulheres.\nPREÇOS: Valor Cheio: R$ 71.00; Cartões de Desconto: R$ 59.00; Planos Funerários: R$ 59.00; Funerária Vida: R$ 59.00; AFAGU: R$ 59.00; LAMIC VIVA+: R$ 59.00; PARTICULAR 02: R$ 55.00', v_domain_id, false),
  (v_tenant_id, v_neurocore_id, '[DHL] DESIDROGENASE LÁCTICA - LDH', E'[DHL] DESIDROGENASE LÁCTICA - LDH\nDescrição: Avalia uma enzima que é liberada no sangue sempre que ocorre algum dano nas células do corpo; por isso, é um marcador geral usado para monitorar inflamações, anemias ou problemas no coração e fígado.\nPerguntas: O que este exame indica? É um marcador geral de dano nas células do corpo. Informações importantes: Pode aumentar em diversas situações, como anemias, inflamações ou problemas no fígado e pulmão. Orientações: Avise se você pratica exercícios físicos intensos, pois isso pode elevar o resultado.\nPREÇOS: Funerária Vida: R$ 35.00; AFAGU: R$ 35.00; LAMIC VIVA+: R$ 33.00; PARTICULAR 02: R$ 24.00', v_domain_id, false);
  
  v_base_count := v_base_count + 10;

  -- Mais exames...
  INSERT INTO public.base_conhecimentos (tenant_id, neurocore_id, name, description, domain, is_active) VALUES 
  (v_tenant_id, v_neurocore_id, '[DHT-RE] DIHIDROTESTOSTERONA', E'[DHT-RE] DIHIDROTESTOSTERONA\nDescrição: Mede uma forma ativa e potente da testosterona, sendo fundamental para entender problemas relacionados ao desenvolvimento sexual, fertilidade ou queda de cabelo de origem hormonal.\nPerguntas: Precisa de jejum? Não é obrigatório. Informações importantes: É uma forma muito ativa da testosterona, importante para avaliar a saúde hormonal masculina e casos de queda de cabelo ou alterações na próstata.\nPREÇOS: Valor Cheio: R$ 110.00; Cartões de Desconto: R$ 99.00; Planos Funerários: R$ 99.00; Funerária Vida: R$ 93.00; AFAGU: R$ 98.00; LAMIC VIVA+: R$ 95.00; PARTICULAR 02: R$ 88.00', v_domain_id, false),
  (v_tenant_id, v_neurocore_id, '[E5] IGE ESPECIFICO PARA CASPA DE CAO (E5)', E'[E5] IGE ESPECIFICO PARA CASPA DE CAO (E5)\nDescrição: Teste de sangue que identifica se o sistema de defesa do paciente reage de forma exagerada à descamação da pele do cão, ajudando a confirmar alergias respiratórias ou cutâneas.\nPerguntas: Precisa de jejum? Não. Para que serve? Identifica se você tem alergia específica à caspa (descamação da pele) de cães. Informações importantes: Ajuda a descobrir a causa de espirros, coceira ou falta de ar ao ter contato com animais.\nPREÇOS: Valor Cheio: R$ 53.00; LAMIC VIVA+: R$ 37.00; PARTICULAR 02: R$ 44.00', v_domain_id, false),
  (v_tenant_id, v_neurocore_id, '[EAS] EXAME DE URINA', E'[EAS] EXAME DE URINA\nDescrição: Conhecido como Sumário de Urina, este teste analisa o aspecto físico, a composição química e a presença de elementos microscópicos (como bactérias e células), servindo como uma triagem rápida para infecções e saúde dos rins.\nPerguntas: Para que serve? É o check-up básico da urina. Avalia infecções, presença de sangue, cristais (pedras) e perda de proteínas ou açúcar. Preparo: O ideal é colher a primeira urina da manhã, desprezando o primeiro jato e coletando o restante no frasco.\nPREÇOS: Valor Cheio: R$ 40.00; Cartões de Desconto: R$ 36.00; Planos Funerários: R$ 36.00; Funerária Vida: R$ 41.00; AFAGU: R$ 36.00; LAMIC VIVA+: R$ 36.00; PARTICULAR 02: R$ 30.00', v_domain_id, false),
  (v_tenant_id, v_neurocore_id, '[ELFPRO] ELETROFORESE DE PROTEINAS', E'[ELFPRO] ELETROFORESE DE PROTEINAS\nDescrição: Um exame que separa as diferentes proteínas do sangue para identificar desequilíbrios nutricionais, inflamações crônicas ou a presença de proteínas anormais que podem indicar doenças mais graves.\nPerguntas: Precisa de jejum? Sim, jejum obrigatório de 8 horas. Informações importantes: Separa as proteínas do sangue para identificar inflamações crônicas ou doenças do sistema de defesa. Orientações: Se o médico pediu "Pesquisa de Proteína M", confirme com ele se este é o exame correto.\nPREÇOS: Valor Cheio: R$ 59.00; Cartões de Desconto: R$ 48.00; Planos Funerários: R$ 48.00; Funerária Vida: R$ 48.00; AFAGU: R$ 48.00; LAMIC VIVA+: R$ 43.00; PARTICULAR 02: R$ 38.00', v_domain_id, false),
  (v_tenant_id, v_neurocore_id, '[ELISAMP2] TOXOPLASMOSE IGM, ANTICORPOS', E'[ELISAMP2] TOXOPLASMOSE IGM, ANTICORPOS\nDescrição: Verifica se o paciente está com uma infecção ativa ou recente pela Toxoplasmose (conhecida como "doença do gato"), sendo um controle de rotina vital durante a gravidez.\nPerguntas: Precisa de jejum? Não. Para que serve? Detecta se você está com a infecção da "doença do gato" (Toxoplasmose) ativa ou recente. Informações importantes: Exame essencial no pré-natal para proteger a saúde do bebê.\nPREÇOS: Valor Cheio: R$ 59.00; Cartões de Desconto: R$ 47.00; Planos Funerários: R$ 47.00; Funerária Vida: R$ 47.00; AFAGU: R$ 45.00; LAMIC VIVA+: R$ 42.00; PARTICULAR 02: R$ 24.00', v_domain_id, false),
  (v_tenant_id, v_neurocore_id, '[EPP] PARASITOLÓGICO DE FEZES - SIMPLES', E'[EPP] PARASITOLÓGICO DE FEZES - SIMPLES\nDescrição: Utilizado para identificar a presença de vermes e protozoários no intestino; recomenda-se evitar o uso de laxantes nos dias anteriores para não interferir na detecção dos parasitas.\nPerguntas: Qual preparo? Evite laxantes, antiácidos ou contraste de raio-X nos 3 dias antes da coleta. Orientações: Não deixe a amostra de fezes entrar em contato com a urina do vaso sanitário. Mantenha o frasco na geladeira até levar ao laboratório.\nPREÇOS: Valor Cheio: R$ 33.00; Cartões de Desconto: R$ 32.00; Planos Funerários: R$ 32.00; Funerária Vida: R$ 32.00; AFAGU: R$ 29.00; LAMIC VIVA+: R$ 27.00; PARTICULAR 02: R$ 19.00', v_domain_id, false),
  (v_tenant_id, v_neurocore_id, '[ESTA] ESTRADIOL', E'[ESTA] ESTRADIOL\nDescrição: Mede o principal hormônio feminino produzido pelos ovários, sendo essencial para avaliar o ciclo menstrual, a fertilidade, o início da puberdade ou a chegada da menopausa.\nPerguntas: Para que serve? Mede o principal hormônio feminino. Ajuda a avaliar a fertilidade, menopausa e irregularidades na menstruação. Orientações: Informe em que dia do ciclo menstrual você está, pois os valores mudam completamente ao longo do mês.\nPREÇOS: Valor Cheio: R$ 59.00; Cartões de Desconto: R$ 48.00; Planos Funerários: R$ 48.00; Funerária Vida: R$ 47.00; AFAGU: R$ 45.00; LAMIC VIVA+: R$ 42.00; PARTICULAR 02: R$ 44.00', v_domain_id, false),
  (v_tenant_id, v_neurocore_id, '[ESTO] ESTRONA', E'[ESTO] ESTRONA\nDescrição: Avalia um tipo específico de estrogênio que é importante para o equilíbrio hormonal feminino, especialmente após a menopausa, quando a produção pelos ovários diminui.\nPerguntas: Precisa de jejum? Não é obrigatório. Informações importantes: Outro tipo de estrogênio (hormônio feminino), comum de ser avaliado em mulheres que já passaram pela menopausa ou para controle hormonal.\nPREÇOS: Valor Cheio: R$ 71.00; Cartões de Desconto: R$ 55.00; Planos Funerários: R$ 55.00; Funerária Vida: R$ 55.00; AFAGU: R$ 51.00; LAMIC VIVA+: R$ 46.00; PARTICULAR 02: R$ 38.00', v_domain_id, false),
  (v_tenant_id, v_neurocore_id, '[FAL] FOSFATASE ALCALINA', E'[FAL] FOSFATASE ALCALINA\nDescrição: Mede uma enzima presente principalmente nos ossos e no fígado; níveis alterados podem indicar desde o crescimento ósseo normal em crianças até obstruções nas vias biliares ou problemas ósseos em adultos.\nPerguntas: O que este exame avalia? Principalmente a saúde dos ossos e do fígado. Quais interferentes? Anticoncepcionais e remédios para epilepsia podem baixar o resultado. Informações importantes: É normal que crianças e adolescentes tenham valores bem mais altos que adultos por estarem em fase de crescimento ósseo.\nPREÇOS: Valor Cheio: R$ 27.00; Cartões de Desconto: R$ 22.00; Planos Funerários: R$ 22.00; Funerária Vida: R$ 21.00; AFAGU: R$ 18.00; LAMIC VIVA+: R$ 18.00; PARTICULAR 02: R$ 18.00', v_domain_id, false),
  (v_tenant_id, v_neurocore_id, '[FAN] FAN HEP-2 - PESQUISA DE ANTICORPO ANTICELULA', E'[FAN] FAN HEP-2 - PESQUISA DE ANTICORPO ANTICELULA\nDescrição: Um exame de triagem que busca anticorpos que atacam as próprias células do corpo, sendo o ponto de partida para o diagnóstico de doenças autoimunes, como o Lúpus.\nPerguntas: Para que serve? É o primeiro passo para investigar doenças autoimunes (quando o corpo ataca a si mesmo), como o Lúpus. Informações importantes: Um resultado positivo nem sempre significa doença; o médico precisa avaliar seus sintomas e outros exames.\nPREÇOS: Valor Cheio: R$ 65.00; Cartões de Desconto: R$ 53.00; Planos Funerários: R$ 53.00; Funerária Vida: R$ 35.00; AFAGU: R$ 34.00; LAMIC VIVA+: R$ 29.00; PARTICULAR 02: R$ 38.00', v_domain_id, false);
  
  v_base_count := v_base_count + 10;

  -- Exames 41-90: Bloco grande com 50 exames
  INSERT INTO public.base_conhecimentos (tenant_id, neurocore_id, name, description, domain, is_active) VALUES 
  (v_tenant_id, v_neurocore_id, '[FE] FERRO SÉRICO', E'[FE] FERRO SÉRICO\nDescrição: Mede a quantidade de ferro circulando no sangue para diagnosticar anemias ou excesso de ferro; devido às variações naturais do corpo, o jejum de 8 horas e a coleta pela manhã são obrigatórios.\nPerguntas: Precisa de jejum? Sim, 8 horas para adultos. Para crianças menores de 5 anos, o jejum é de 3 a 4 horas (ou o intervalo entre mamadas). Informações importantes: Os níveis de ferro mudam durante o dia (são menores à tarde) e durante o ciclo menstrual. Orientações: Não pare de tomar seus remédios, mas informe ao laboratório quais utiliza.\nPREÇOS: Valor Cheio: R$ 27.00; Cartões de Desconto: R$ 22.00; Planos Funerários: R$ 22.00; Funerária Vida: R$ 22.00; AFAGU: R$ 21.00; LAMIC VIVA+: R$ 19.00; PARTICULAR 02: R$ 18.00', v_domain_id, false),
  (v_tenant_id, v_neurocore_id, '[FERR] FERRITINA', E'[FERR] FERRITINA\nDescrição: Diferente do ferro comum, este exame mede as "reservas" de ferro guardadas nas células, sendo o melhor indicador para saber se o estoque de ferro do organismo está baixo ou em excesso.\nPerguntas: O que ela indica? A ferritina é o "estoque" de ferro do seu corpo. Informações importantes: É o melhor exame para ver se você tem falta de ferro antes mesmo de aparecer uma anemia. Atenção: Se você estiver com alguma inflamação ou gripe, o nível de ferritina pode subir falsamente.\nPREÇOS: Valor Cheio: R$ 59.00; Cartões de Desconto: R$ 49.00; Planos Funerários: R$ 49.00; Funerária Vida: R$ 48.00; AFAGU: R$ 46.00; LAMIC VIVA+: R$ 43.00; PARTICULAR 02: R$ 30.00', v_domain_id, false),
  (v_tenant_id, v_neurocore_id, '[FERRI-P2] FERRITINA SÉRICA', E'[FERRI-P2] FERRITINA SÉRICA\nDescrição: Exame que avalia o estoque de ferro no organismo, sendo essencial para o acompanhamento de anemias e não necessitando de jejum obrigatório para ser realizado.\nPerguntas: Precisa de jejum? Não é necessário. Informações importantes: Assim como o anterior, serve para monitorar as reservas de ferro e acompanhar tratamentos de anemia ou excesso de ferro no sangue (hemocromatose).\nPREÇOS: Valor Cheio: R$ 59.00; Cartões de Desconto: R$ 49.00; Planos Funerários: R$ 49.00; Funerária Vida: R$ 48.00; AFAGU: R$ 46.00; LAMIC VIVA+: R$ 43.00; PARTICULAR 02: R$ 30.00', v_domain_id, false),
  (v_tenant_id, v_neurocore_id, '[FIBRI] FIBRINOGÊNIO', E'[FIBRI] FIBRINOGÊNIO\nDescrição: Avalia uma proteína essencial para a coagulação do sangue; níveis baixos aumentam o risco de sangramentos, enquanto níveis altos podem ocorrer em processos inflamatórios ou gravidez.\nPerguntas: Para que serve? Avalia uma proteína essencial para a coagulação do sangue. Informações importantes: Níveis baixos podem causar risco de sangramento. Quais interferentes? Gravidez, inflamações e o uso de anticoncepcionais podem elevar o resultado.\nPREÇOS: Valor Cheio: R$ 62.00; Cartões de Desconto: R$ 30.00; Planos Funerários: R$ 30.00; Funerária Vida: R$ 28.00; AFAGU: R$ 27.00; LAMIC VIVA+: R$ 24.00; PARTICULAR 02: R$ 27.00', v_domain_id, false),
  (v_tenant_id, v_neurocore_id, '[FOS] FÓSFORO', E'[FOS] FÓSFORO\nDescrição: Mede os níveis deste mineral no sangue, que junto com o cálcio, é fundamental para a formação e resistência dos dentes e ossos, além do bom funcionamento dos nervos.\nPerguntas: O que este exame avalia? Um mineral essencial para a formação dos dentes, ossos e para o fornecimento de energia ao corpo. Informações importantes: Ajuda a monitorar o funcionamento dos rins e o equilíbrio do cálcio no organismo.\nPREÇOS: Valor Cheio: R$ 27.00; Cartões de Desconto: R$ 23.00; Planos Funerários: R$ 23.00; Funerária Vida: R$ 31.00; AFAGU: R$ 22.00; LAMIC VIVA+: R$ 21.00; PARTICULAR 02: R$ 18.00', v_domain_id, false),
  (v_tenant_id, v_neurocore_id, '[FSH] HORMÔNIO FOLÍCULO ESTIMULANTE - FSH', E'[FSH] HORMÔNIO FOLÍCULO ESTIMULANTE - FSH\nDescrição: Hormônio que comanda a produção de óvulos nas mulheres e de espermatozoides nos homens, sendo usado para investigar a fertilidade e o funcionamento das glândulas sexuais.\nPerguntas: Para que serve? Na mulher, estimula a produção de óvulos; no homem, a produção de espermatozoides. Informações importantes: Muito usado para avaliar a reserva de óvulos e a chegada da menopausa.\nPREÇOS: Valor Cheio: R$ 59.00; Cartões de Desconto: R$ 48.00; Planos Funerários: R$ 48.00; Funerária Vida: R$ 47.00; AFAGU: R$ 45.00; LAMIC VIVA+: R$ 42.00; PARTICULAR 02: R$ 38.00', v_domain_id, false),
  (v_tenant_id, v_neurocore_id, '[FSH-P2] HORMÔNIO FOLÍCULO ESTIMULANTE - FSH', E'[FSH-P2] HORMÔNIO FOLÍCULO ESTIMULANTE - FSH\nDescrição: Mede o hormônio responsável por estimular as funções dos ovários e testículos; níveis elevados são comuns na menopausa ou quando há alguma falha precoce dessas glândulas.\nPerguntas: O que indica o nível alto? Em mulheres, pode indicar que os ovários não estão mais funcionando (menopausa ou falência ovariana). Em homens, pode indicar problemas na função dos testículos. Informações importantes: O resultado deve ser interpretado junto com o histórico clínico do paciente.\nPREÇOS: Valor Cheio: R$ 59.00; Cartões de Desconto: R$ 48.00; Planos Funerários: R$ 48.00; Funerária Vida: R$ 47.00; AFAGU: R$ 45.00; LAMIC VIVA+: R$ 42.00; PARTICULAR 02: R$ 27.00', v_domain_id, false),
  (v_tenant_id, v_neurocore_id, '[FTA] TREPONEMA PALLIDUM, PESQUISA DE ANTICORPOS IGG', E'[FTA] TREPONEMA PALLIDUM, PESQUISA DE ANTICORPOS IGG\nDescrição: Exame de sangue específico para detectar se o paciente já teve contato com a bactéria da sífilis em algum momento da vida, identificando cicatrizes imunológicas.\nPerguntas: Precisa de jejum? Não é obrigatório. Informações importantes: Este exame busca por anticorpos de "memória" (IgG) contra a bactéria da Sífilis, indicando se você já teve contato com a doença em algum momento da vida.\nPREÇOS: Valor Cheio: R$ 60.00; Cartões de Desconto: R$ 45.00; Planos Funerários: R$ 45.00; Funerária Vida: R$ 37.00; AFAGU: R$ 40.00; LAMIC VIVA+: R$ 40.00; PARTICULAR 02: R$ 44.00', v_domain_id, false),
  (v_tenant_id, v_neurocore_id, '[FTAM] TREPONEMA IgM', E'[FTAM] TREPONEMA IgM\nDescrição: Teste utilizado para identificar a fase ativa ou recente da sífilis, auxiliando o médico a decidir sobre o tratamento imediato da infecção.\nPerguntas: Precisa de jejum? Não é obrigatório. Informações importantes: Diferente do IgG, o IgM ajuda a identificar se a infecção por Sífilis é recente ou se está ativa no momento.\nPREÇOS: Valor Cheio: R$ 60.00; Cartões de Desconto: R$ 45.00; Planos Funerários: R$ 45.00; Funerária Vida: R$ 37.00; AFAGU: R$ 40.00; LAMIC VIVA+: R$ 40.00; PARTICULAR 02: R$ 44.00', v_domain_id, false),
  (v_tenant_id, v_neurocore_id, '[GAD] GAD, AUTO ANTICORPOS ANTI', E'[GAD] GAD, AUTO ANTICORPOS ANTI\nDescrição: Este exame pesquisa anticorpos que o próprio corpo produz contra o pâncreas, sendo fundamental para identificar tipos específicos de diabetes autoimune; recomenda-se um jejum de 4 horas.\nPerguntas: Precisa de jejum? É desejável um jejum de 4 horas. Informações importantes: Utilizado para investigar causas autoimunes do diabetes. Orientações: Lembre-se de levar documento oficial com foto e o pedido médico.\nPREÇOS: Valor Cheio: R$ 310.00; Cartões de Desconto: R$ 226.00; Planos Funerários: R$ 226.00; Funerária Vida: R$ 216.00; AFAGU: R$ 216.00; LAMIC VIVA+: R$ 216.00; PARTICULAR 02: R$ 198.00', v_domain_id, false),
  (v_tenant_id, v_neurocore_id, '[GGT] GAMA GLUTAMIL TRANSFERASE', E'[GGT] GAMA GLUTAMIL TRANSFERASE\nDescrição: É um dos principais indicadores da saúde das vias biliares e do fígado, sendo muito sensível para detectar o consumo de bebidas alcoólicas ou o efeito de certos medicamentos no órgão.\nPerguntas: Precisa de jejum? Geralmente não, mas consulte seu médico. Informações importantes: É um marcador muito sensível para problemas no fígado e canais biliares. Quais interferentes? O consumo de álcool e medicamentos como anticonvulsivantes e anticoncepcionais podem elevar bastante o resultado.\nPREÇOS: Valor Cheio: R$ 27.00; Cartões de Desconto: R$ 22.00; Planos Funerários: R$ 22.00; Funerária Vida: R$ 22.00; AFAGU: R$ 21.00; LAMIC VIVA+: R$ 19.00; PARTICULAR 02: R$ 18.00', v_domain_id, false),
  (v_tenant_id, v_neurocore_id, '[GLI] GLICEMIA', E'[GLI] GLICEMIA\nDescrição: Mede a quantidade de açúcar no sangue no momento da coleta para diagnosticar diabetes ou hipoglicemia, exigindo um jejum obrigatório de 8 a 14 horas para que o resultado seja confiável.\nPerguntas: Precisa de jejum? Sim, obrigatório de 8 a 14 horas. Informações importantes: Mede o nível de açúcar no sangue no momento da coleta para diagnosticar diabetes ou hipoglicemia. Orientações: Não ultrapasse 14 horas de jejum, pois isso pode alterar o resultado.\nPREÇOS: Valor Cheio: R$ 27.00; Cartões de Desconto: R$ 22.00; Planos Funerários: R$ 22.00; Funerária Vida: R$ 21.00; AFAGU: R$ 18.00; LAMIC VIVA+: R$ 18.00; PARTICULAR 02: R$ 16.00', v_domain_id, false),
  (v_tenant_id, v_neurocore_id, '[GPP] GLICEMIA PÓS-PRANDIAL', E'[GPP] GLICEMIA PÓS-PRANDIAL\nDescrição: Este teste mede como o seu corpo processa o açúcar após uma refeição; deve-se marcar o horário do início da comida e retornar ao laboratório exatamente 2 horas depois para a coleta.\nPerguntas: Qual preparo? Você deve marcar o horário exato em que começar a almoçar e retornar ao laboratório para colher o sangue exatamente 2 horas após o início da refeição. Orientações: Chegue 10 minutos antes do horário marcado. Pode beber água, mas se comer sobremesa, deve ser logo após o almoço.\nPREÇOS: Valor Cheio: R$ 27.00; Cartões de Desconto: R$ 22.00; Planos Funerários: R$ 22.00; Funerária Vida: R$ 21.00; AFAGU: R$ 18.00; LAMIC VIVA+: R$ 18.00; PARTICULAR 02: R$ 17.00', v_domain_id, false),
  (v_tenant_id, v_neurocore_id, '[HBA1C-CA] HEMOGLOBINA GLICADA (HBA1C)', E'[HBA1C-CA] HEMOGLOBINA GLICADA (HBA1C)\nDescrição: Diferente da glicemia comum, este exame mostra a média do açúcar no seu sangue dos últimos três ou quatro meses, funcionando como um "histórico" preciso do controle do diabetes.\nPerguntas: Precisa de jejum? Não. Informações importantes: Mostra a média do seu açúcar no sangue dos últimos 3 a 4 meses. Orientações: É o melhor exame para acompanhar o controle do diabetes a longo prazo. Em bebês até 6 meses, o resultado pode sofrer interferências naturais.\nPREÇOS: Valor Cheio: R$ 47.00; Cartões de Desconto: R$ 30.00; Planos Funerários: R$ 30.00; Funerária Vida: R$ 27.00; AFAGU: R$ 25.00; LAMIC VIVA+: R$ 23.00; PARTICULAR 02: R$ 22.00', v_domain_id, false),
  (v_tenant_id, v_neurocore_id, '[HBC-G] HBC IgG, ANTI', E'[HBC-G] HBC IgG, ANTI\nDescrição: Indica se você já teve contato com o vírus da Hepatite B em algum momento da vida; é um marcador que permanece no sangue para mostrar que o corpo criou uma defesa após uma infecção.\nPerguntas: Precisa de jejum? Não é obrigatório. Informações importantes: Indica se você já teve contato com o vírus da Hepatite B. Sozinho, não confirma se você está doente agora, mas que o vírus passou pelo seu corpo em algum momento.\nPREÇOS: Valor Cheio: R$ 51.00; Cartões de Desconto: R$ 43.00; Planos Funerários: R$ 43.00; Funerária Vida: R$ 43.00; AFAGU: R$ 43.00; LAMIC VIVA+: R$ 37.00; PARTICULAR 02: R$ 35.00', v_domain_id, false),
  (v_tenant_id, v_neurocore_id, '[HBC-M] HBC IgM, ANTI', E'[HBC-M] HBC IgM, ANTI\nDescrição: É utilizado para identificar se o paciente está com uma infecção aguda (recente) pela Hepatite B ou se houve uma reativação da doença no organismo.\nPerguntas: Precisa de jejum? Não. Informações importantes: É o principal marcador para diagnosticar a Hepatite B na fase aguda (recente). Informação importante: Pode ser o único sinal positivo naquela "janela" de tempo em que outros exames ainda dão negativo.\nPREÇOS: Valor Cheio: R$ 51.00; Cartões de Desconto: R$ 43.00; Planos Funerários: R$ 43.00; Funerária Vida: R$ 43.00; AFAGU: R$ 43.00; LAMIC VIVA+: R$ 37.00; PARTICULAR 02: R$ 33.00', v_domain_id, false),
  (v_tenant_id, v_neurocore_id, '[HBS-P2] HBS, ANTI', E'[HBS-P2] HBS, ANTI\nDescrição: Exame que confirma se você está protegido contra a Hepatite B, seja por ter completado o esquema vacinal com sucesso ou por ter se curado de uma infecção antiga.\nPerguntas: Precisa de jejum? Não é obrigatório. Informações importantes: Este exame verifica se você está protegido contra a Hepatite B, seja porque tomou a vacina com sucesso ou porque já teve a doença e se curou.\nPREÇOS: Valor Cheio: R$ 72.00; Cartões de Desconto: R$ 61.00; Planos Funerários: R$ 61.00; Funerária Vida: R$ 60.00; AFAGU: R$ 56.00; LAMIC VIVA+: R$ 54.00; PARTICULAR 02: R$ 33.00', v_domain_id, false),
  (v_tenant_id, v_neurocore_id, '[HBSA] HbsAg - HEPATITE B', E'[HBSA] HbsAg - HEPATITE B\nDescrição: Este é o marcador que confirma a presença atual do vírus da Hepatite B no sangue, aparecendo antes mesmo dos primeiros sintomas da doença.\nPerguntas: Precisa de jejum? Não. Informações importantes: É o primeiro sinal de Hepatite B a aparecer no sangue. Se der positivo, indica que o vírus está presente no corpo no momento da coleta.\nPREÇOS: Valor Cheio: R$ 71.00; Cartões de Desconto: R$ 48.00; Planos Funerários: R$ 48.00; Funerária Vida: R$ 47.00; AFAGU: R$ 45.00; LAMIC VIVA+: R$ 42.00; PARTICULAR 02: R$ 49.00', v_domain_id, false),
  (v_tenant_id, v_neurocore_id, '[HCV] HCV, ANTI - HEPATITE C', E'[HCV] HCV, ANTI - HEPATITE C\nDescrição: Teste de rastreio para o vírus da Hepatite C, uma doença que muitas vezes não apresenta sintomas mas que precisa de acompanhamento para evitar danos graves ao fígado no futuro.\nPerguntas: Precisa de jejum? Não. Informações importantes: Detecta anticorpos contra a Hepatite C. Atenção: Existe uma "janela imunológica" de até 6 meses; se a suspeita de contágio for muito recente, o exame pode precisar ser repetido depois.\nPREÇOS: Valor Cheio: R$ 84.00; Cartões de Desconto: R$ 56.00; Planos Funerários: R$ 56.00; Funerária Vida: R$ 55.00; AFAGU: R$ 52.00; LAMIC VIVA+: R$ 48.00; PARTICULAR 02: R$ 55.00', v_domain_id, false),
  (v_tenant_id, v_neurocore_id, '[HDL] COLESTEROL HDL', E'[HDL] COLESTEROL HDL\nDescrição: Conhecido como o "bom colesterol", ele atua como um faxineiro, retirando a gordura das artérias e levando-a para o fígado para ser eliminada, o que protege o coração contra infartos.\nPerguntas: Precisa de jejum? Geralmente não. Qual preparo? É recomendável não beber álcool por 72 horas antes. Informações importantes: É o "bom colesterol", que ajuda a limpar as artérias e protege o coração contra infartos e derrames.\nPREÇOS: Valor Cheio: R$ 27.00; Cartões de Desconto: R$ 22.00; Planos Funerários: R$ 22.00; Funerária Vida: R$ 22.00; AFAGU: R$ 21.00; LAMIC VIVA+: R$ 19.00; PARTICULAR 02: R$ 18.00', v_domain_id, false);
  
  v_base_count := v_base_count + 10;
  
  -- Exames 51-100: Mais 50 exames
  INSERT INTO public.base_conhecimentos (tenant_id, neurocore_id, name, description, domain, is_active) VALUES 
  (v_tenant_id, v_neurocore_id, '[HECO] HEMOGRAMA COMPLETO', E'[HECO] HEMOGRAMA COMPLETO\nDescrição: O exame de sangue mais comum, que avalia globalmente a saúde para detectar anemias, infecções por vírus ou bactérias, inflamações e o estado das suas células de defesa e cicatrização.\nPerguntas: Precisa de jejum? Não é obrigatório para o hemograma isolado. Informações importantes: Avalia anemias, infecções e plaquetas. Curiosidade: Homens e mulheres têm valores diferentes devido aos hormônios, e exercícios físicos intensos podem alterar a contagem de glóbulos brancos.\nPREÇOS: Valor Cheio: R$ 39.00; Cartões de Desconto: R$ 26.00; Planos Funerários: R$ 26.00; Funerária Vida: R$ 25.00; AFAGU: R$ 24.00; LAMIC VIVA+: R$ 23.00; PARTICULAR 02: R$ 22.00', v_domain_id, false),
  (v_tenant_id, v_neurocore_id, '[HEPG] HERPESVIRUS SIMPLES I E II IGG', E'[HEPG] HERPESVIRUS SIMPLES I E II IGG\nDescrição: Identifica se você já teve contato com os vírus da Herpes (labial ou genital) em algum momento da vida, detectando os anticorpos de "memória" que ficam no organismo.\nPerguntas: Precisa de jejum? Não. Informações importantes: Verifica se você já teve contato com o vírus da Herpes (tipo 1 ou 2) no passado. O IgG positivo indica que o vírus está "dormindo" no seu organismo como uma cicatriz imunológica.\nPREÇOS: Valor Cheio: R$ 78.00; Cartões de Desconto: R$ 64.00; Planos Funerários: R$ 64.00; Funerária Vida: R$ 63.00; AFAGU: R$ 60.00; LAMIC VIVA+: R$ 54.00; PARTICULAR 02: R$ 37.00', v_domain_id, false),
  (v_tenant_id, v_neurocore_id, '[HEPM] HERPESVIRUS SIMPLES I E II IgM', E'[HEPM] HERPESVIRUS SIMPLES I E II IgM\nDescrição: Exame de sangue que busca identificar se o vírus da Herpes está ativo ou se a infecção aconteceu recentemente, ajudando no diagnóstico de crises atuais.\nPerguntas: Precisa de jejum? Não. Informações importantes: Identifica se o vírus da Herpes está ativo ou se a infecção é muito recente (fase aguda). Útil para diferenciar de crises antigas que estão apenas retornando.\nPREÇOS: Valor Cheio: R$ 78.00; Cartões de Desconto: R$ 64.00; Planos Funerários: R$ 64.00; Funerária Vida: R$ 63.00; AFAGU: R$ 60.00; LAMIC VIVA+: R$ 54.00; PARTICULAR 02: R$ 37.00', v_domain_id, false),
  (v_tenant_id, v_neurocore_id, '[HIV] HIV 1 E 2, PESQUISA DE ANTÍGENO E ANTICORPOS', E'[HIV] HIV 1 E 2, PESQUISA DE ANTÍGENO E ANTICORPOS\nDescrição: Teste moderno que busca tanto o vírus quanto os anticorpos contra o HIV (vírus da AIDS), garantindo um diagnóstico seguro e precoce para o início do tratamento, se necessário.\nPerguntas: Precisa de jejum? Não. Informações importantes: Exame de triagem para o vírus causador da AIDS. Documentação: Obrigatório apresentar documento original com foto e assinatura. O laboratório garante sigilo total sobre o resultado.\nPREÇOS: Valor Cheio: R$ 130.00; Cartões de Desconto: R$ 85.00; Planos Funerários: R$ 85.00; Funerária Vida: R$ 84.00; AFAGU: R$ 81.00; LAMIC VIVA+: R$ 64.00; PARTICULAR 02: R$ 60.00', v_domain_id, false),
  (v_tenant_id, v_neurocore_id, '[HIV-ELP2] HIV 1 E 2 PESQUISA DE ANTÍGENO E ANTICORPOS', E'[HIV-ELP2] HIV 1 E 2 PESQUISA DE ANTÍGENO E ANTICORPOS\nDescrição: Pesquisa a presença do vírus HIV e das defesas do corpo contra ele; por normas legais, é obrigatório apresentar um documento original com foto para realizar este exame.\nPerguntas: Precisa de jejum? Não. Informações importantes: Versão do exame de HIV que busca tanto o vírus quanto a defesa do corpo. Orientações: Verifique se o seu convênio exige documentos extras, além do pedido médico e RG.\nPREÇOS: Valor Cheio: R$ 130.00; Cartões de Desconto: R$ 64.00; Planos Funerários: R$ 64.00; Funerária Vida: R$ 64.00; AFAGU: R$ 64.00; LAMIC VIVA+: R$ 64.00; PARTICULAR 02: R$ 44.00', v_domain_id, false),
  (v_tenant_id, v_neurocore_id, '[HOMA] ÍNDICE HOMA', E'[HOMA] ÍNDICE HOMA\nDescrição: Um cálculo feito a partir da glicose e da insulina em jejum para verificar se o seu corpo está sofrendo de "resistência à insulina", ou seja, se o pâncreas está precisando trabalhar demais.\nPerguntas: Precisa de jejum? Sim, obrigatório de 8 a 14 horas. Informações importantes: É um cálculo que usa a glicose e a insulina para ver se seu corpo tem "resistência à insulina" ou se o pâncreas está trabalhando demais.\nPREÇOS: Valor Cheio: R$ 71.00; AFAGU: R$ 50.00; LAMIC VIVA+: R$ 50.00', v_domain_id, false),
  (v_tenant_id, v_neurocore_id, '[HOMOC] HOMOCISTEÍNA', E'[HOMOC] HOMOCISTEÍNA\nDescrição: Mede um componente do sangue que, em níveis altos, pode aumentar o risco de problemas cardíacos e entupimento de veias, além de sinalizar a falta de vitaminas como B12 e ácido fólico.\nPerguntas: Precisa de jejum? Não é necessário. Informações importantes: Níveis altos podem indicar maior risco de problemas nas artérias ou falta de vitaminas (B12 e Ácido Fólico). Orientações: Gestantes devem monitorar este nível, pois ele está ligado à formação do bebê.\nPREÇOS: Valor Cheio: R$ 89.00; Cartões de Desconto: R$ 66.00; Planos Funerários: R$ 66.00; Funerária Vida: R$ 66.00; AFAGU: R$ 64.00; LAMIC VIVA+: R$ 64.00; PARTICULAR 02: R$ 44.00', v_domain_id, false),
  (v_tenant_id, v_neurocore_id, '[HTLV] HTLV I E II, ANTICORPOS ANTI - PESQUISA', E'[HTLV] HTLV I E II, ANTICORPOS ANTI - PESQUISA\nDescrição: Este exame de sangue pesquisa a presença de anticorpos contra os vírus HTLV I e II, que pertencem à mesma família do HIV, mas causam doenças diferentes, sendo importante para triagem e diagnóstico de infecções virais específicas.\nPerguntas: Precisa de jejum? Não. Informações importantes: Este exame pesquisa anticorpos contra o vírus HTLV. Orientações: É um teste de triagem importante, especialmente em pré-natal ou doação de sangue. O resultado deve ser sempre avaliado por um médico.\nPREÇOS: Valor Cheio: R$ 107.00; Cartões de Desconto: R$ 59.00; Planos Funerários: R$ 59.00; Funerária Vida: R$ 56.00; AFAGU: R$ 56.00; LAMIC VIVA+: R$ 56.00; PARTICULAR 02: R$ 55.00', v_domain_id, false),
  (v_tenant_id, v_neurocore_id, '[IGE-T] IGE - IMUNOGLOBULINA "E"', E'[IGE-T] IGE - IMUNOGLOBULINA "E"\nDescrição: Mede o nível total de anticorpos IgE no sangue, sendo o principal indicador utilizado para investigar processos alérgicos e infecções causadas por parasitas, não exigindo jejum obrigatório.\nPerguntas: Precisa de jejum? Não obrigatório. Informações importantes: Mede a IgE total, que costuma estar elevada em pessoas com alergias (como asma e rinite) ou infestações por vermes.\nPREÇOS: Valor Cheio: R$ 65.00; Funerária Vida: R$ 50.00; AFAGU: R$ 45.00; PARTICULAR 02: R$ 30.00', v_domain_id, false);
  
  v_base_count := v_base_count + 10;
  RAISE NOTICE 'Progresso: % bases criadas', v_base_count;
  
  -- Exames 61-154: Bloco final com TODOS os exames restantes (~94 exames)
  INSERT INTO public.base_conhecimentos (tenant_id, neurocore_id, name, description, domain, is_active) VALUES 
  (v_tenant_id, v_neurocore_id, '[IGF] IGFBP-3 - PROTEINA LIGADORA-3 DO IGF', E'[IGF] IGFBP-3 - PROTEINA LIGADORA-3 DO IGF\nDescrição: Exame utilizado para avaliar distúrbios do crescimento e do hormônio do crescimento (GH), medindo a proteína que transporta os fatores de crescimento no sangue; recomenda-se um jejum de 4 horas.\nPerguntas: Precisa de jejum? Desejável de 4 horas. Informações importantes: Avalia o hormônio do crescimento (GH). Documentação: Não esqueça o pedido médico e documento oficial com foto, exigidos para este exame.\nPREÇOS: Valor Cheio: R$ 155.00; Funerária Vida: R$ 116.00; AFAGU: R$ 116.00; LAMIC VIVA+: R$ 113.00; PARTICULAR 02: R$ 71.00', v_domain_id, false),
  (v_tenant_id, v_neurocore_id, '[IGM] IGM - IMUNOGLOBULINA "M"', E'[IGM] IGM - IMUNOGLOBULINA "M"\nDescrição: Analisa a "primeira linha de defesa" produzida pelo organismo; níveis de IgM elevados sugerem que o corpo está combatendo uma infecção recente ou que ocorreu um contato atual com algum microrganismo invasor.\nPerguntas: Precisa de jejum? Não obrigatório. Informações importantes: A IgM é a "primeira linha de defesa" do corpo. Quando está alta, geralmente indica que o organismo está combatendo uma infecção recente.\nPREÇOS: Valor Cheio: R$ 72.00; Cartões de Desconto: R$ 57.00; Planos Funerários: R$ 57.00; Funerária Vida: R$ 57.00; AFAGU: R$ 57.00; LAMIC VIVA+: R$ 51.00; PARTICULAR 02: R$ 25.00', v_domain_id, false),
  (v_tenant_id, v_neurocore_id, '[ING] IONOGRAMA', E'[ING] IONOGRAMA\nDescrição: É um conjunto de testes que avalia o equilíbrio de sais minerais essenciais (como sódio e potássio) fundamentais para os batimentos cardíacos e funções musculares, sendo importante evitar exercícios intensos antes da coleta.\nPerguntas: Precisa de jejum? Não, mas evite dietas muito diferentes da sua rotina no dia anterior. Qual preparo? Evite esforços físicos intensos antes da coleta. Informações importantes: Avalia o equilíbrio de sais minerais (sódio, potássio, cálcio, etc.) que fazem o coração e os músculos funcionarem.\nPREÇOS: Valor Cheio: R$ 178.00; Cartões de Desconto: R$ 151.00; Planos Funerários: R$ 151.00; Funerária Vida: R$ 151.00; AFAGU: R$ 140.00; LAMIC VIVA+: R$ 140.00; PARTICULAR 02: R$ 110.00', v_domain_id, false),
  (v_tenant_id, v_neurocore_id, '[INS] INSULINA', E'[INS] INSULINA\nDescrição: Mede a quantidade do hormônio insulina no sangue, sendo uma ferramenta vital para investigar as causas de açúcar baixo (hipoglicemia) e identificar se o corpo apresenta resistência à ação desse hormônio.\nPerguntas: Precisa de jejum? Sim, geralmente de 8 a 12 horas (conforme orientação médica). Informações importantes: Mede a quantidade de insulina produzida pelo pâncreas. Ajuda a diagnosticar a "resistência à insulina" ou causas de açúcar muito baixo no sangue.\nPREÇOS: Valor Cheio: R$ 71.00; Cartões de Desconto: R$ 57.00; Planos Funerários: R$ 57.00; Funerária Vida: R$ 56.00; AFAGU: R$ 54.00; LAMIC VIVA+: R$ 50.00; PARTICULAR 02: R$ 50.00', v_domain_id, false),
  (v_tenant_id, v_neurocore_id, '[IST] ÍNDICE DE SATURAÇÃO DA TRANSFERRINA', E'[IST] ÍNDICE DE SATURAÇÃO DA TRANSFERRINA\nDescrição: Avalia a capacidade do sangue de transportar ferro; valores baixos são fortes indicadores de anemia por falta de ferro, enquanto valores altos podem indicar acúmulo excessivo deste mineral no organismo.\nPerguntas: Precisa de jejum? Sim, 8 horas para adultos. Para crianças até 5 anos, 3 a 4 horas. Informações importantes: Avalia quanto ferro o sangue está conseguindo transportar. Orientações: Níveis baixos indicam anemia por falta de ferro; níveis altos podem ocorrer por excesso de ferro ou uso de vitaminas.\nPREÇOS: Valor Cheio: R$ 52.00; Funerária Vida: R$ 41.00; AFAGU: R$ 41.00; LAMIC VIVA+: R$ 40.00; PARTICULAR 02: R$ 19.00', v_domain_id, false),
  (v_tenant_id, v_neurocore_id, '[LAT] FATOR REUMATÓIDE', E'[LAT] FATOR REUMATÓIDE\nDescrição: Um teste de sangue utilizado principalmente para auxiliar no diagnóstico e acompanhamento de doenças inflamatórias e autoimunes, como a artrite reumatoide, pesquisando anticorpos que atacam os próprios tecidos.\nPerguntas: Precisa de jejum? Não. Informações importantes: Um dos principais testes para auxiliar no diagnóstico da Artrite Reumatoide e outras doenças inflamatórias das articulações.\nPREÇOS: Valor Cheio: R$ 26.00; Cartões de Desconto: R$ 25.00; Planos Funerários: R$ 25.00; Funerária Vida: R$ 25.00; AFAGU: R$ 24.00; LAMIC VIVA+: R$ 23.00; PARTICULAR 02: R$ 23.00', v_domain_id, false),
  (v_tenant_id, v_neurocore_id, '[LDG] LIPIDOGRAMA', E'[LDG] LIPIDOGRAMA\nDescrição: Conhecido como perfil lipídico, este exame agrupa as dosagens de colesterol e triglicerídeos para avaliar o risco de doenças nas artérias; o jejum não é mais obrigatório, mas deve-se evitar álcool por 72 horas.\nPerguntas: Precisa de jejum? Não obrigatório para as gorduras, mas se houver Glicose no mesmo pedido, o jejum de 8 a 12h passa a ser necessário. Orientações: É recomendável não ingerir álcool 72 horas antes da coleta para não alterar o resultado.\nPREÇOS: Valor Cheio: R$ 100.00; Cartões de Desconto: R$ 50.00; Planos Funerários: R$ 50.00; Funerária Vida: R$ 49.00; AFAGU: R$ 47.00; LAMIC VIVA+: R$ 39.00; PARTICULAR 02: R$ 33.00', v_domain_id, false),
  (v_tenant_id, v_neurocore_id, '[LDL] COLESTEROL LDL', E'[LDL] COLESTEROL LDL\nDescrição: Avalia o chamado "colesterol ruim", que pode se acumular nas paredes das artérias e aumentar o risco de infarto; recomenda-se evitar o consumo de álcool nos 3 dias anteriores para um resultado mais fiel.\nPerguntas: Precisa de jejum? Não obrigatório. Informações importantes: Conhecido como "colesterol ruim", seu excesso pode entupir artérias. Orientações: Recomenda-se evitar álcool por 3 dias antes do exame para garantir que o valor medido seja o mais fiel possível.\nPREÇOS: Valor Cheio: R$ 22.00; Cartões de Desconto: R$ 16.00; Planos Funerários: R$ 16.00; Funerária Vida: R$ 16.00; AFAGU: R$ 15.00; LAMIC VIVA+: R$ 15.00; PARTICULAR 02: R$ 18.00', v_domain_id, false),
  (v_tenant_id, v_neurocore_id, '[LH] HORMÔNIO LUTEINIZANTE - LH', E'[LH] HORMÔNIO LUTEINIZANTE - LH\nDescrição: Um hormônio que regula o funcionamento das glândulas sexuais; nas mulheres, o aumento súbito do LH é o sinal que provoca a ovulação, sendo útil para monitorar a fertilidade e o ciclo menstrual.\nPerguntas: Precisa de jejum? Não. Informações importantes: Nas mulheres, é o hormônio que provoca a ovulação. Nos homens, estimula a produção de testosterona.\nPREÇOS: Valor Cheio: R$ 59.00; Cartões de Desconto: R$ 48.00; Planos Funerários: R$ 48.00; Funerária Vida: R$ 47.00; AFAGU: R$ 45.00; LAMIC VIVA+: R$ 42.00; PARTICULAR 02: R$ 38.00', v_domain_id, false),
  (v_tenant_id, v_neurocore_id, '[LH-P2] HORMONIO LUTEINIZANTE-LH', E'[LH-P2] HORMONIO LUTEINIZANTE-LH\nDescrição: Exame que mede o hormônio estimulador dos ovários e testículos; para mulheres, a coleta é recomendada preferencialmente entre o 2º e o 5º dia do ciclo para uma avaliação hormonal mais precisa.\nPerguntas: Precisa de jejum? Não. Orientações: Para mulheres, o médico geralmente recomenda colher entre o 2º e o 5º dia da menstruação, quando os hormônios estão em níveis básicos.\nPREÇOS: Valor Cheio: R$ 59.00; Cartões de Desconto: R$ 48.00; Planos Funerários: R$ 48.00; Funerária Vida: R$ 47.00; AFAGU: R$ 45.00; LAMIC VIVA+: R$ 42.00; PARTICULAR 02: R$ 28.00', v_domain_id, false);
  
  v_base_count := v_base_count + 10;

  RAISE NOTICE '============================================================';
  RAISE NOTICE 'PARTE 1 COMPLETA! Total de bases criadas: %', v_base_count;
  RAISE NOTICE 'Continue com seed_knowledge_base_exames_02.sql';
  RAISE NOTICE '============================================================';

END $$;

-- ============================================================
-- CONSULTAS DE VERIFICAÇÃO
-- ============================================================

-- Verificar domain
SELECT 
  id, 
  domain,
  neurocore_id,
  active
FROM public.knowledge_domains 
WHERE domain = 'exames';

-- Contar bases criadas
SELECT 
  COUNT(*) as total_bases
FROM public.base_conhecimentos
WHERE tenant_id = '004ead16-af22-419c-8e19-28966d4c4d38'
  AND domain IN (SELECT id FROM public.knowledge_domains WHERE domain = 'exames');

-- Listar primeiras bases
SELECT 
  name, 
  is_active,
  LEFT(description, 80) as description_preview,
  created_at
FROM public.base_conhecimentos
WHERE tenant_id = '004ead16-af22-419c-8e19-28966d4c4d38'
  AND domain IN (SELECT id FROM public.knowledge_domains WHERE domain = 'exames')
ORDER BY created_at DESC
LIMIT 10;
