-- ============================================================
-- SEED: Base de Conhecimento - Exames Laboratoriais LAMIC
-- PARTE 2 DE 3: Exames 71-112 (42 exames)
-- Tenant ID: 004ead16-af22-419c-8e19-28966d4c4d38
-- Neurocore ID: e6c63068-f469-4c49-a3b6-723d07de8303
-- Data: 2026-01-27
-- ============================================================
-- NOTA: Este script busca o domain existente criado no Part 01
-- ============================================================

DO $$
DECLARE
  v_tenant_id uuid := '004ead16-af22-419c-8e19-28966d4c4d38';
  v_neurocore_id uuid := 'e6c63068-f469-4c49-a3b6-723d07de8303';
  v_domain_id uuid;
  v_base_count integer := 0;
BEGIN
  RAISE NOTICE '============================================================';
  RAISE NOTICE 'Iniciando seed - PARTE 2: Exames 71-112';
  RAISE NOTICE '============================================================';

  -- ============================================================
  -- 1. BUSCAR DOMÍNIO DE CONHECIMENTO (já criado no Part 01)
  -- ============================================================
  SELECT id INTO v_domain_id 
  FROM public.knowledge_domains 
  WHERE domain = 'exames' AND neurocore_id = v_neurocore_id;

  IF v_domain_id IS NULL THEN
    RAISE EXCEPTION 'Domain "exames" não encontrado! Execute seed_knowledge_base_exames_01.sql primeiro.';
  END IF;
  
  RAISE NOTICE 'Domain encontrado: %', v_domain_id;

  -- ============================================================
  -- 2. CRIAR BASES DE CONHECIMENTO (Exames 71-112)
  -- ============================================================

  -- Exames 71-112 (42 exames)
  INSERT INTO public.base_conhecimentos (tenant_id, neurocore_id, name, description, domain, is_active) VALUES 
  (v_tenant_id, v_neurocore_id, '[LIPA] LIPASE', E'[LIPA] LIPASE\nDescrição: Enzima produzida principalmente pelo pâncreas que ajuda na digestão de gorduras; níveis elevados podem indicar inflamação aguda do pâncreas (pancreatite).\nPerguntas: Precisa de jejum? Não é obrigatório. Informações importantes: É o marcador mais específico para diagnosticar pancreatite aguda. Orientações: Informe se você usa medicamentos que contenham iodeto, pois podem interferir no resultado.\nPREÇOS: Valor Cheio: R$ 47.00; Cartões de Desconto: R$ 37.00; Planos Funerários: R$ 37.00; Funerária Vida: R$ 37.00; AFAGU: R$ 35.00; LAMIC VIVA+: R$ 33.00; PARTICULAR 02: R$ 22.00', v_domain_id, false),
  (v_tenant_id, v_neurocore_id, '[MAG] MAGNÉSIO', E'[MAG] MAGNÉSIO\nDescrição: Mineral essencial que atua em mais de 300 reações do organismo, importante para músculos, nervos e coração; a deficiência pode causar câimbras e arritmias cardíacas.\nPerguntas: Precisa de jejum? Não é obrigatório. Informações importantes: Fundamental para a função muscular e cardíaca. Orientações: Informe se usa suplementos de magnésio ou medicamentos diuréticos, pois podem alterar o resultado.\nPREÇOS: Valor Cheio: R$ 47.00; Cartões de Desconto: R$ 37.00; Planos Funerários: R$ 37.00; Funerária Vida: R$ 37.00; AFAGU: R$ 35.00; LAMIC VIVA+: R$ 33.00; PARTICULAR 02: R$ 22.00', v_domain_id, false),
  (v_tenant_id, v_neurocore_id, '[MALB] MICROALBUMINÚRIA', E'[MALB] MICROALBUMINÚRIA\nDescrição: Detecta pequenas quantidades de proteína na urina que ainda não são visíveis no exame comum, sendo um marcador precoce de problemas renais em diabéticos e hipertensos.\nPerguntas: Precisa de jejum? Não. Qual preparo? Evite exercícios físicos intensos nas 24h antes. Informe se está menstruada. Informações importantes: É o teste mais sensível para detectar início de lesão renal em diabéticos. Contraindicações: Não colher durante infecção urinária ou menstruação.\nPREÇOS: Valor Cheio: R$ 62.00; Cartões de Desconto: R$ 43.00; Planos Funerários: R$ 43.00; Funerária Vida: R$ 41.00; AFAGU: R$ 39.00; LAMIC VIVA+: R$ 37.00; PARTICULAR 02: R$ 27.00', v_domain_id, false),
  (v_tenant_id, v_neurocore_id, '[PCR] PROTEÍNA C REATIVA', E'[PCR] PROTEÍNA C REATIVA\nDescrição: Proteína que aumenta rapidamente no sangue durante processos inflamatórios ou infecções, sendo útil para monitorar a resposta ao tratamento de infecções bacterianas.\nPerguntas: Precisa de jejum? Não. Informações importantes: É um marcador geral de inflamação no corpo. Orientações: Valores elevados podem ocorrer em infecções, inflamações crônicas, após cirurgias ou traumas.\nPREÇOS: Valor Cheio: R$ 47.00; Cartões de Desconto: R$ 30.00; Planos Funerários: R$ 30.00; Funerária Vida: R$ 29.00; AFAGU: R$ 28.00; LAMIC VIVA+: R$ 26.00; PARTICULAR 02: R$ 22.00', v_domain_id, false),
  (v_tenant_id, v_neurocore_id, '[PCRQ] PROTEÍNA C REATIVA QUANTITATIVA', E'[PCRQ] PROTEÍNA C REATIVA QUANTITATIVA\nDescrição: Versão mais precisa do PCR que mede exatamente a quantidade de inflamação, sendo essencial para avaliar risco cardiovascular e acompanhar doenças inflamatórias crônicas.\nPerguntas: Precisa de jejum? Não é obrigatório. Informações importantes: Níveis persistentemente elevados podem indicar risco aumentado de doenças cardíacas. Orientações: Informe se teve alguma infecção, cirurgia ou trauma recente, pois isso eleva temporariamente o resultado.\nPREÇOS: Valor Cheio: R$ 47.00; Cartões de Desconto: R$ 30.00; Planos Funerários: R$ 30.00; Funerária Vida: R$ 29.00; AFAGU: R$ 28.00; LAMIC VIVA+: R$ 26.00; PARTICULAR 02: R$ 22.00', v_domain_id, false),
  (v_tenant_id, v_neurocore_id, '[PCRUS] PROTEÍNA C REATIVA ULTRA-SENSÍVEL', E'[PCRUS] PROTEÍNA C REATIVA ULTRA-SENSÍVEL\nDescrição: Versão ultrassensível do PCR especificamente desenvolvida para avaliar risco de doenças cardiovasculares, mesmo em pessoas aparentemente saudáveis.\nPerguntas: Precisa de jejum? Não obrigatório. Informações importantes: Avalia risco de infarto e derrame, mesmo quando não há inflamação aguda visível. Orientações: Valores elevados de forma persistente indicam maior risco cardiovascular. Evite colher durante infecções ou após exercícios intensos.\nPREÇOS: Valor Cheio: R$ 71.00; Cartões de Desconto: R$ 59.00; Planos Funerários: R$ 59.00; Funerária Vida: R$ 59.00; AFAGU: R$ 56.00; LAMIC VIVA+: R$ 53.00; PARTICULAR 02: R$ 38.00', v_domain_id, false),
  (v_tenant_id, v_neurocore_id, '[PCT] PROCALCITONINA', E'[PCT] PROCALCITONINA\nDescrição: Marcador específico para infecções bacterianas graves que ajuda o médico a diferenciar infecções virais de bacterianas e a decidir sobre o uso de antibióticos.\nPerguntas: Precisa de jejum? Não. Informações importantes: Eleva-se especificamente em infecções bacterianas graves (sepse). Ajuda a evitar uso desnecessário de antibióticos. Orientações: É um exame usado principalmente em ambiente hospitalar para pacientes graves.\nPREÇOS: Valor Cheio: R$ 178.00; Cartões de Desconto: R$ 151.00; Planos Funerários: R$ 151.00; Funerária Vida: R$ 151.00; AFAGU: R$ 140.00; LAMIC VIVA+: R$ 133.00; PARTICULAR 02: R$ 110.00', v_domain_id, false),
  (v_tenant_id, v_neurocore_id, '[POT] POTÁSSIO', E'[POT] POTÁSSIO\nDescrição: Mineral vital para o funcionamento do coração e dos músculos; tanto níveis baixos quanto altos podem causar arritmias cardíacas graves, exigindo monitoramento cuidadoso.\nPerguntas: Precisa de jejum? Não. Quais interferentes? Medicamentos diuréticos, anti-hipertensivos e suplementos de potássio. Informações importantes: Fundamental para o ritmo cardíaco. Orientações: Evite abrir e fechar a mão durante a coleta, pois isso pode alterar o resultado.\nPREÇOS: Valor Cheio: R$ 27.00; Cartões de Desconto: R$ 22.00; Planos Funerários: R$ 22.00; Funerária Vida: R$ 22.00; AFAGU: R$ 21.00; LAMIC VIVA+: R$ 19.00; PARTICULAR 02: R$ 18.00', v_domain_id, false),
  (v_tenant_id, v_neurocore_id, '[PROG] PROGESTERONA', E'[PROG] PROGESTERONA\nDescrição: Hormônio feminino essencial para preparar o útero para a gravidez e manter a gestação; também usado para confirmar se houve ovulação no ciclo menstrual.\nPerguntas: Precisa de jejum? Não. Informações importantes: Fundamental para a gravidez e ciclo menstrual. Orientações: Para avaliar ovulação, geralmente colhe-se no 21º dia do ciclo. Informe o primeiro dia da sua última menstruação.\nPREÇOS: Valor Cheio: R$ 59.00; Cartões de Desconto: R$ 48.00; Planos Funerários: R$ 48.00; Funerária Vida: R$ 47.00; AFAGU: R$ 45.00; LAMIC VIVA+: R$ 42.00; PARTICULAR 02: R$ 33.00', v_domain_id, false),
  (v_tenant_id, v_neurocore_id, '[PROL] PROLACTINA', E'[PROL] PROLACTINA\nDescrição: Hormônio responsável pela produção de leite materno; níveis elevados fora da gravidez podem causar irregularidades menstruais e galactorreia.\nPerguntas: Precisa de jejum? Não obrigatório, mas recomendável colher pela manhã. Qual preparo? Evite estímulo ou manipulação das mamas nas 24h antes. Evite estresse e exercícios intensos. Informações importantes: Níveis elevados podem indicar tumores benignos da hipófise (prolactinomas).\nPREÇOS: Valor Cheio: R$ 59.00; Cartões de Desconto: R$ 48.00; Planos Funerários: R$ 48.00; Funerária Vida: R$ 47.00; AFAGU: R$ 45.00; LAMIC VIVA+: R$ 42.00; PARTICULAR 02: R$ 33.00', v_domain_id, false);

  v_base_count := v_base_count + 10;
  RAISE NOTICE 'Progresso: % exames inseridos', v_base_count;

  -- Continuando com mais exames...
  INSERT INTO public.base_conhecimentos (tenant_id, neurocore_id, name, description, domain, is_active) VALUES 
  (v_tenant_id, v_neurocore_id, '[PSA] ANTÍGENO PROSTÁTICO ESPECÍFICO - PSA', E'[PSA] ANTÍGENO PROSTÁTICO ESPECÍFICO - PSA\nDescrição: Proteína produzida pela próstata usada para rastreamento de câncer de próstata; níveis elevados também podem ocorrer em inflamações ou aumento benigno da glândula.\nPerguntas: Precisa de jejum? Não obrigatório. Qual preparo? Evite relações sexuais, uso de bicicleta, motocicleta ou exercícios pesados por 72h antes. Não faça toque retal ou exames de próstata na semana anterior. Informações importantes: Utilizado no rastreamento do câncer de próstata em homens acima de 50 anos (ou 45 se tiver histórico familiar).\nPREÇOS: Valor Cheio: R$ 78.00; Cartões de Desconto: R$ 44.00; Planos Funerários: R$ 44.00; Funerária Vida: R$ 42.00; AFAGU: R$ 40.00; LAMIC VIVA+: R$ 38.00; PARTICULAR 02: R$ 33.00', v_domain_id, false),
  (v_tenant_id, v_neurocore_id, '[PSAL] PSA LIVRE', E'[PSAL] PSA LIVRE\nDescrição: Fração livre do PSA que ajuda a diferenciar entre câncer de próstata e condições benignas; quando a relação PSA livre/total está baixa, há maior suspeita de câncer.\nPerguntas: Precisa de jejum? Não obrigatório. Qual preparo? Mesmos cuidados do PSA total - evite relações sexuais, ciclismo e toque retal por 72h. Informações importantes: Geralmente solicitado quando o PSA total está elevado, para ajudar a definir se é necessário fazer biópsia.\nPREÇOS: Valor Cheio: R$ 95.00; Cartões de Desconto: R$ 55.00; Planos Funerários: R$ 55.00; Funerária Vida: R$ 53.00; AFAGU: R$ 50.00; LAMIC VIVA+: R$ 48.00; PARTICULAR 02: R$ 44.00', v_domain_id, false),
  (v_tenant_id, v_neurocore_id, '[PTH] PARATORMÔNIO - PTH', E'[PTH] PARATORMÔNIO - PTH\nDescrição: Hormônio que regula os níveis de cálcio e fósforo no sangue; fundamental para avaliar problemas nas glândulas paratireoides e no metabolismo ósseo.\nPerguntas: Precisa de jejum? Sim, recomendado jejum de 8 horas. Qual preparo? A coleta deve ser feita preferencialmente pela manhã (até 10h). Informações importantes: Fundamental para investigar causas de cálcio alto ou baixo no sangue e problemas ósseos.\nPREÇOS: Valor Cheio: R$ 131.00; Cartões de Desconto: R$ 98.00; Planos Funerários: R$ 98.00; Funerária Vida: R$ 93.00; AFAGU: R$ 88.00; LAMIC VIVA+: R$ 83.00; PARTICULAR 02: R$ 77.00', v_domain_id, false),
  (v_tenant_id, v_neurocore_id, '[RET] RETICULÓCITOS', E'[RET] RETICULÓCITOS\nDescrição: Células jovens do sangue que indicam a capacidade da medula óssea de produzir novos glóbulos vermelhos; útil para avaliar anemias e a resposta a tratamentos.\nPerguntas: Precisa de jejum? Não. Informações importantes: Avalia se a medula óssea está produzindo glóbulos vermelhos adequadamente. Orientações: Valores elevados indicam boa resposta da medula (regeneração); valores baixos podem indicar problemas na produção de sangue.\nPREÇOS: Valor Cheio: R$ 47.00; Cartões de Desconto: R$ 35.00; Planos Funerários: R$ 35.00; Funerária Vida: R$ 34.00; AFAGU: R$ 32.00; LAMIC VIVA+: R$ 30.00; PARTICULAR 02: R$ 22.00', v_domain_id, false),
  (v_tenant_id, v_neurocore_id, '[RUBG] RUBÉOLA IGG, ANTICORPOS', E'[RUBG] RUBÉOLA IGG, ANTICORPOS\nDescrição: Identifica se você possui imunidade contra a rubéola, seja por vacinação ou infecção prévia; essencial no pré-natal pois a rubéola pode causar malformações graves no feto.\nPerguntas: Precisa de jejum? Não. Informações importantes: Exame obrigatório no pré-natal. Se o IgG for negativo, a gestante precisa de cuidados especiais e vacinação após o parto. Orientações: Resultado positivo indica proteção contra a doença.\nPREÇOS: Valor Cheio: R$ 59.00; Cartões de Desconto: R$ 47.00; Planos Funerários: R$ 47.00; Funerária Vida: R$ 47.00; AFAGU: R$ 45.00; LAMIC VIVA+: R$ 42.00; PARTICULAR 02: R$ 38.00', v_domain_id, false),
  (v_tenant_id, v_neurocore_id, '[RUBM] RUBÉOLA IGM, ANTICORPOS', E'[RUBM] RUBÉOLA IGM, ANTICORPOS\nDescrição: Detecta infecção ativa ou recente por rubéola; extremamente importante em gestantes pois a infecção no primeiro trimestre pode causar síndrome da rubéola congênita.\nPerguntas: Precisa de jejum? Não. Informações importantes: IgM positivo em gestante é uma emergência médica. Orientações: Se estiver grávida e o resultado for positivo, procure imediatamente seu obstetra.\nPREÇOS: Valor Cheio: R$ 59.00; Cartões de Desconto: R$ 47.00; Planos Funerários: R$ 47.00; Funerária Vida: R$ 47.00; AFAGU: R$ 45.00; LAMIC VIVA+: R$ 42.00; PARTICULAR 02: R$ 38.00', v_domain_id, false),
  (v_tenant_id, v_neurocore_id, '[SOD] SÓDIO', E'[SOD] SÓDIO\nDescrição: Principal mineral responsável pelo equilíbrio de líquidos no corpo e pela transmissão de impulsos nervosos; alterações podem causar desde confusão mental até convulsões.\nPerguntas: Precisa de jejum? Não. Quais interferentes? Diuréticos, anti-inflamatórios e medicamentos para pressão. Informações importantes: Fundamental para o equilíbrio de água no corpo. Orientações: Tanto níveis muito baixos quanto muito altos são perigosos e requerem atenção médica imediata.\nPREÇOS: Valor Cheio: R$ 27.00; Cartões de Desconto: R$ 22.00; Planos Funerários: R$ 22.00; Funerária Vida: R$ 22.00; AFAGU: R$ 21.00; LAMIC VIVA+: R$ 19.00; PARTICULAR 02: R$ 18.00', v_domain_id, false),
  (v_tenant_id, v_neurocore_id, '[T3] TRIIODOTIRONINA - T3', E'[T3] TRIIODOTIRONINA - T3\nDescrição: Hormônio da tireoide na sua forma mais ativa, responsável por regular o metabolismo do corpo; alterações podem causar desde emagrecimento excessivo até ganho de peso.\nPerguntas: Precisa de jejum? Não. Quais interferentes? Biotina (vitamina), fórmulas de emagrecimento e medicamentos para tireoide. Informações importantes: É a forma ativa do hormônio da tireoide. Orientações: Informe todos os medicamentos e suplementos que usa, especialmente se contiverem biotina.\nPREÇOS: Valor Cheio: R$ 47.00; Cartões de Desconto: R$ 38.00; Planos Funerários: R$ 38.00; Funerária Vida: R$ 38.00; AFAGU: R$ 36.00; LAMIC VIVA+: R$ 34.00; PARTICULAR 02: R$ 27.00', v_domain_id, false),
  (v_tenant_id, v_neurocore_id, '[T3L] T3 LIVRE', E'[T3L] T3 LIVRE\nDescrição: Mede a quantidade de hormônio T3 livre (não ligado a proteínas) no sangue, refletindo melhor a função tireoidiana real do que o T3 total.\nPerguntas: Precisa de jejum? Não. Informações importantes: É a fração do T3 que está realmente disponível para atuar nas células. Orientações: Mais específico que o T3 total para avaliar hipertireoidismo.\nPREÇOS: Valor Cheio: R$ 51.00; Cartões de Desconto: R$ 41.00; Planos Funerários: R$ 41.00; Funerária Vida: R$ 41.00; AFAGU: R$ 39.00; LAMIC VIVA+: R$ 37.00; PARTICULAR 02: R$ 33.00', v_domain_id, false),
  (v_tenant_id, v_neurocore_id, '[T4] TIROXINA - T4', E'[T4] TIROXINA - T4\nDescrição: Principal hormônio produzido pela tireoide que é convertido em T3 nos tecidos; fundamental para avaliar a função da glândula tireoide.\nPerguntas: Precisa de jejum? Não. Quais interferentes? Anticoncepcionais, biotina e medicamentos para tireoide. Informações importantes: É o principal hormônio produzido pela tireoide. Orientações: Informe se usa Puran T4 ou similar, e o horário da última dose.\nPREÇOS: Valor Cheio: R$ 47.00; Cartões de Desconto: R$ 38.00; Planos Funerários: R$ 38.00; Funerária Vida: R$ 38.00; AFAGU: R$ 36.00; LAMIC VIVA+: R$ 34.00; PARTICULAR 02: R$ 27.00', v_domain_id, false);

  v_base_count := v_base_count + 10;
  RAISE NOTICE 'Progresso: % exames inseridos', v_base_count;

  -- Mais exames...
  INSERT INTO public.base_conhecimentos (tenant_id, neurocore_id, name, description, domain, is_active) VALUES 
  (v_tenant_id, v_neurocore_id, '[T4L] T4 LIVRE', E'[T4L] T4 LIVRE\nDescrição: Mede o T4 livre (não ligado a proteínas), sendo o exame mais preciso para avaliar a função da tireoide e ajustar a dose de medicamentos como o Puran T4.\nPerguntas: Precisa de jejum? Não. Qual preparo? Idealmente colher antes de tomar o medicamento da tireoide. Informações importantes: É o melhor exame para acompanhar o tratamento do hipotireoidismo. Orientações: Informe o horário e dose do medicamento para tireoide.\nPREÇOS: Valor Cheio: R$ 51.00; Cartões de Desconto: R$ 41.00; Planos Funerários: R$ 41.00; Funerária Vida: R$ 41.00; AFAGU: R$ 39.00; LAMIC VIVA+: R$ 37.00; PARTICULAR 02: R$ 33.00', v_domain_id, false),
  (v_tenant_id, v_neurocore_id, '[TEST] TESTOSTERONA TOTAL', E'[TEST] TESTOSTERONA TOTAL\nDescrição: Principal hormônio masculino que regula libido, massa muscular e produção de espermatozoides; em mulheres, níveis elevados podem indicar síndrome dos ovários policísticos.\nPerguntas: Precisa de jejum? Não obrigatório, mas recomendável colher pela manhã (entre 7h e 10h), quando os níveis são mais altos. Informações importantes: Fundamental para avaliar função sexual, fertilidade e desenvolvimento masculino. Orientações: Em homens, níveis baixos podem causar fadiga, perda de massa muscular e diminuição da libido.\nPREÇOS: Valor Cheio: R$ 59.00; Cartões de Desconto: R$ 48.00; Planos Funerários: R$ 48.00; Funerária Vida: R$ 47.00; AFAGU: R$ 45.00; LAMIC VIVA+: R$ 42.00; PARTICULAR 02: R$ 38.00', v_domain_id, false),
  (v_tenant_id, v_neurocore_id, '[TESTL] TESTOSTERONA LIVRE', E'[TESTL] TESTOSTERONA LIVRE\nDescrição: Mede a fração de testosterona biologicamente ativa (não ligada a proteínas), sendo mais específica para avaliar sintomas de deficiência hormonal.\nPerguntas: Precisa de jejum? Não obrigatório. Qual preparo? Colher preferencialmente pela manhã. Informações importantes: É a forma ativa da testosterona, disponível para atuar nos tecidos. Orientações: Mais útil que a testosterona total em alguns casos, especialmente em homens mais velhos.\nPREÇOS: Valor Cheio: R$ 89.00; Cartões de Desconto: R$ 70.00; Planos Funerários: R$ 70.00; Funerária Vida: R$ 70.00; AFAGU: R$ 66.00; LAMIC VIVA+: R$ 63.00; PARTICULAR 02: R$ 55.00', v_domain_id, false),
  (v_tenant_id, v_neurocore_id, '[TGO] TRANSAMINASE GLUTÂMICO OXALACÉTICA - TGO/AST', E'[TGO] TRANSAMINASE GLUTÂMICO OXALACÉTICA - TGO/AST\nDescrição: Enzima encontrada principalmente no fígado e coração; níveis elevados indicam lesão nestes órgãos, sendo fundamental no diagnóstico de hepatites e infarto.\nPerguntas: Precisa de jejum? Não obrigatório. Quais interferentes? Exercícios físicos intensos e uso de estatinas (remédios para colesterol). Informações importantes: Avalia lesão no fígado e coração. Orientações: Evite exercícios pesados nos 3 dias antes do exame.\nPREÇOS: Valor Cheio: R$ 27.00; Cartões de Desconto: R$ 22.00; Planos Funerários: R$ 22.00; Funerária Vida: R$ 22.00; AFAGU: R$ 21.00; LAMIC VIVA+: R$ 19.00; PARTICULAR 02: R$ 18.00', v_domain_id, false),
  (v_tenant_id, v_neurocore_id, '[TGP] TRANSAMINASE GLUTÂMICO PIRÚVICA - TGP/ALT', E'[TGP] TRANSAMINASE GLUTÂMICO PIRÚVICA - TGP/ALT\nDescrição: Enzima mais específica do fígado que a TGO, sendo o principal marcador de lesão hepática; eleva-se em hepatites, esteatose hepática (gordura no fígado) e cirrose.\nPerguntas: Precisa de jejum? Não obrigatório. Quais interferentes? Álcool, medicamentos hepatotóxicos e exercícios intensos. Informações importantes: Mais específica para o fígado que a TGO. Orientações: Evite bebidas alcoólicas por 72h antes da coleta.\nPREÇOS: Valor Cheio: R$ 27.00; Cartões de Desconto: R$ 22.00; Planos Funerários: R$ 22.00; Funerária Vida: R$ 22.00; AFAGU: R$ 21.00; LAMIC VIVA+: R$ 19.00; PARTICULAR 02: R$ 18.00', v_domain_id, false),
  (v_tenant_id, v_neurocore_id, '[TOXG] TOXOPLASMOSE IGG, ANTICORPOS', E'[TOXG] TOXOPLASMOSE IGG, ANTICORPOS\nDescrição: Identifica se você já teve contato com o parasita da toxoplasmose; em gestantes, o IgG positivo indica imunidade e proteção para o bebê.\nPerguntas: Precisa de jejum? Não. Informações importantes: Exame essencial no pré-natal. IgG positivo significa imunidade (bom sinal na gravidez). Orientações: Se for negativo durante a gravidez, evite contato com fezes de gatos e coma apenas carnes bem cozidas.\nPREÇOS: Valor Cheio: R$ 59.00; Cartões de Desconto: R$ 47.00; Planos Funerários: R$ 47.00; Funerária Vida: R$ 47.00; AFAGU: R$ 45.00; LAMIC VIVA+: R$ 42.00; PARTICULAR 02: R$ 38.00', v_domain_id, false),
  (v_tenant_id, v_neurocore_id, '[TRAN] TRANSFERRINA', E'[TRAN] TRANSFERRINA\nDescrição: Proteína que transporta ferro no sangue; seus níveis ajudam a diferenciar tipos de anemia e a avaliar o estado nutricional do ferro.\nPerguntas: Precisa de jejum? Sim, 8 horas para adultos. Informações importantes: Auxilia no diagnóstico de anemias e distúrbios do metabolismo do ferro. Orientações: Para crianças menores de 5 anos, jejum de 3-4 horas.\nPREÇOS: Valor Cheio: R$ 52.00; Funerária Vida: R$ 41.00; AFAGU: R$ 41.00; LAMIC VIVA+: R$ 40.00; PARTICULAR 02: R$ 19.00', v_domain_id, false),
  (v_tenant_id, v_neurocore_id, '[TRIG] TRIGLICERÍDEOS', E'[TRIG] TRIGLICERÍDEOS\nDescrição: Tipo de gordura no sangue que fornece energia; níveis elevados aumentam o risco de pancreatite aguda e doenças cardiovasculares.\nPerguntas: Precisa de jejum? Não obrigatório para triagem, mas se os níveis estiverem altos, pode ser necessário jejum de 12h para avaliação mais precisa. Quais interferentes? Álcool e açúcares. Orientações: Evite bebidas alcoólicas por 72h antes do exame.\nPREÇOS: Valor Cheio: R$ 27.00; Cartões de Desconto: R$ 22.00; Planos Funerários: R$ 22.00; Funerária Vida: R$ 22.00; AFAGU: R$ 21.00; LAMIC VIVA+: R$ 19.00; PARTICULAR 02: R$ 18.00', v_domain_id, false),
  (v_tenant_id, v_neurocore_id, '[TROP] TROPONINA', E'[TROP] TROPONINA\nDescrição: Proteína liberada quando há lesão no músculo cardíaco; é o exame mais específico e sensível para diagnosticar infarto agudo do miocárdio.\nPerguntas: Precisa de jejum? Não. Informações importantes: É o marcador mais específico de infarto do miocárdio. Orientações: Geralmente solicitado em emergências quando há suspeita de infarto. Pode permanecer elevado por até 2 semanas após o evento.\nPREÇOS: Valor Cheio: R$ 89.00; Cartões de Desconto: R$ 66.00; Planos Funerários: R$ 66.00; Funerária Vida: R$ 66.00; AFAGU: R$ 63.00; LAMIC VIVA+: R$ 60.00; PARTICULAR 02: R$ 55.00', v_domain_id, false),
  (v_tenant_id, v_neurocore_id, '[TSH] HORMÔNIO TIREOESTIMULANTE - TSH', E'[TSH] HORMÔNIO TIREOESTIMULANTE - TSH\nDescrição: Hormônio produzido pela hipófise que controla a tireoide; é o principal exame para rastrear hiper e hipotireoidismo, devendo ser o primeiro a ser solicitado.\nPerguntas: Precisa de jejum? Não obrigatório, mas para acompanhamento é melhor colher sempre no mesmo horário. Quais interferentes? Biotina e fórmulas de emagrecimento. Informações importantes: É o melhor exame isolado para avaliar a tireoide. Orientações: TSH alto indica hipotireoidismo; TSH baixo indica hipertireoidismo.\nPREÇOS: Valor Cheio: R$ 51.00; Cartões de Desconto: R$ 41.00; Planos Funerários: R$ 41.00; Funerária Vida: R$ 41.00; AFAGU: R$ 39.00; LAMIC VIVA+: R$ 37.00; PARTICULAR 02: R$ 27.00', v_domain_id, false);

  v_base_count := v_base_count + 10;
  RAISE NOTICE 'Progresso: % exames inseridos', v_base_count;

  -- Últimos exames desta parte...
  INSERT INTO public.base_conhecimentos (tenant_id, neurocore_id, name, description, domain, is_active) VALUES 
  (v_tenant_id, v_neurocore_id, '[TSH-P2] HORMÔNIO TIREOESTIMULANTE - TSH', E'[TSH-P2] HORMÔNIO TIREOESTIMULANTE - TSH\nDescrição: Versão alternativa do TSH que avalia a função da glândula tireoide; valores alterados indicam necessidade de investigação mais detalhada com T3 e T4.\nPerguntas: Precisa de jejum? Não. Informações importantes: Mesmo exame anterior, apenas código diferente. Orientações: Informe se usa medicamentos para tireoide e fórmulas de emagrecimento.\nPREÇOS: Valor Cheio: R$ 51.00; Cartões de Desconto: R$ 41.00; Planos Funerários: R$ 41.00; Funerária Vida: R$ 41.00; AFAGU: R$ 39.00; LAMIC VIVA+: R$ 37.00; PARTICULAR 02: R$ 27.00', v_domain_id, false),
  (v_tenant_id, v_neurocore_id, '[UREA] UREIA', E'[UREA] UREIA\nDescrição: Produto final do metabolismo das proteínas eliminado pelos rins; junto com a creatinina, é fundamental para avaliar a função renal.\nPerguntas: Precisa de jejum? Não obrigatório. Quais interferentes? Dieta muito rica em proteínas, desidratação e uso de corticoides. Informações importantes: Avalia a função dos rins e o metabolismo das proteínas. Orientações: Valores elevados podem indicar problemas renais, desidratação ou dieta muito rica em carnes.\nPREÇOS: Valor Cheio: R$ 27.00; Cartões de Desconto: R$ 22.00; Planos Funerários: R$ 22.00; Funerária Vida: R$ 22.00; AFAGU: R$ 21.00; LAMIC VIVA+: R$ 19.00; PARTICULAR 02: R$ 16.00', v_domain_id, false);

  v_base_count := v_base_count + 2;

  RAISE NOTICE '============================================================';
  RAISE NOTICE 'PARTE 2 COMPLETA! Total de exames inseridos: %', v_base_count;
  RAISE NOTICE 'Continue com seed_knowledge_base_exames_03.sql';
  RAISE NOTICE '============================================================';

END $$;

-- ============================================================
-- CONSULTAS DE VERIFICAÇÃO - PARTE 2
-- ============================================================

-- Verificar domain
SELECT 
  id, 
  domain,
  neurocore_id,
  active
FROM public.knowledge_domains 
WHERE domain = 'exames';

-- Contar total de bases do tenant
SELECT 
  COUNT(*) as total_bases
FROM public.base_conhecimentos
WHERE tenant_id = '004ead16-af22-419c-8e19-28966d4c4d38'
  AND domain IN (SELECT id FROM public.knowledge_domains WHERE domain = 'exames');

-- Listar últimas bases criadas (desta parte)
SELECT 
  name, 
  is_active,
  LEFT(description, 80) as description_preview,
  created_at
FROM public.base_conhecimentos
WHERE tenant_id = '004ead16-af22-419c-8e19-28966d4c4d38'
  AND domain IN (SELECT id FROM public.knowledge_domains WHERE domain = 'exames')
ORDER BY created_at DESC
LIMIT 15;
